--!strict
local Players=game:GetService("Players");local ReplicatedStorage=game:GetService("ReplicatedStorage");local Config=require(ReplicatedStorage.Modules.GameConfig);local Race=require(script.Parent.Services.RaceService);local Maps=require(script.Parent.Services.MapService);local Items=require(script.Parent.Services.ItemService);local Events=require(script.Parent.Services.GameplayEventService);local remotes=require(script.Parent.Services.RemoteService).Ensure();local cooldown:{[Player]:boolean}={}
local function playerFrom(hit:BasePart):Player?local n:Instance?=hit;while n and n~=workspace do if n:IsA("Model")and n:FindFirstChildOfClass("Humanoid")then return Players:GetPlayerFromCharacter(n)end;n=n.Parent end;return nil end
local function restore(p:Player)local d=Race.Get(p);if not d or not d.IsRacing or cooldown[p]then return end;cooldown[p]=true;Items.ClearEffects(p);if d.LastValidCFrame then Race.Teleport(p,d.LastValidCFrame)end;local c=p.Character;if c then local ff=Instance.new("ForceField");ff.Visible=false;ff.Parent=c;task.delay(Config.RespawnProtectionTime,function()if ff.Parent then ff:Destroy()end end)end;task.delay(Config.RespawnProtectionTime,function()cooldown[p]=nil end)end
local function bind(_:string,map:Folder)
	local checkpoints=map:FindFirstChild("Checkpoints")
	if checkpoints then for _,cp in checkpoints:GetChildren()do if cp:IsA("BasePart")then cp.Touched:Connect(function(hit)local p=playerFrom(hit);local d=p and Race.Get(p);local index=cp:GetAttribute("CheckpointIndex");if p and d and Race.State=="Racing"and d.IsRacing and typeof(index)=="number"and index==d.CurrentCheckpoint+1 then d.CurrentCheckpoint=index;d.SegmentProgress=0;d.ProgressReachedAt=os.clock();d.LastValidCFrame=cp.CFrame*CFrame.new(0,0,4);print(string.format("[Checkpoint] %s reached checkpoint %d",p.Name,index));remotes.PlayerProgressUpdated:FireClient(p,{checkpoint=index,totalCheckpoints=#checkpoints:GetChildren()});remotes.GameplayFeedback:FireClient(p,{type="Checkpoint",value=index});Events.Event:Fire(p,"Checkpoint",1);Race.ProgressChanged:Fire(p)end end)end end end
	local kill=map:FindFirstChild("KillFloor");if kill and kill:IsA("BasePart")then kill.Touched:Connect(function(hit)local p=playerFrom(hit);if p then restore(p)end end)end
end
Maps.Loaded.Event:Connect(bind);Players.PlayerRemoving:Connect(function(p)cooldown[p]=nil end)
