--!strict
local Players=game:GetService("Players");local Lobby=require(script.Parent.Services.LobbyService);local Mode=require(script.Parent.Services.ModeService);local Tower=require(script.Parent.Services.TowerService);local Profiles=require(script.Parent.Services.PlayerProfileService);local Rank=require(script.Parent.Services.RankService);local remotes=require(script.Parent.Services.RemoteService).Ensure();local rate:{[Player]:number}={}
local function sendRank(p:Player)local profile=Profiles.GetProfile(p);if not profile then return end;local points=profile.RankedRace.RankPoints;local tier=Rank.Resolve(points);remotes.RankUpdated:FireClient(p,{points=points,displayName=Rank.Display(points),wins=profile.RankedRace.RankedWins,nextPoints=tier.MinimumPoints+100})end
local function added(p:Player)Mode.Get(p);p.CharacterAdded:Connect(function()task.delay(.2,function()if p.Parent==Players and Mode.Get(p).IsInLobby then Lobby.Place(p)end end)end);task.delay(.5,function()if p.Parent==Players then Lobby.Return(p);sendRank(p)end end)end
Players.PlayerAdded:Connect(added);for _,p in Players:GetPlayers()do added(p)end
remotes.ReturnToLobby.OnServerEvent:Connect(function(p)if os.clock()-(rate[p]or 0)<1 then return end;rate[p]=os.clock();local state=Mode.Get(p);if state.CurrentMode=="RankedRace"and state.IsInMatch then Profiles.IncrementValue(p,"RankedRace.AbandonCount",1);local profile=Profiles.GetProfile(p);if profile then Profiles.UpdateValue(p,"RankedRace.RankPoints",math.max(0,profile.RankedRace.RankPoints-10))end end;Lobby.Return(p);sendRank(p)end)
remotes.RequestModeState.OnServerEvent:Connect(function(p)
	local session=Tower.Session(p);if not session then remotes.ModeStateChanged:FireClient(p,Mode.Payload(p));return end
	local ui={Preparing="TowerPreparing",Countdown="TowerCountdown",Running="TowerRunning",Finished="TowerResults",Exited="Lobby"};remotes.ModeStateChanged:FireClient(p,Mode.Payload(p,ui[session.state]));local profile=Profiles.GetProfile(p)
	remotes.TowerProgressUpdated:FireClient(p,{state=session.state,floor=session.currentFloor,total=session.floorCount,best=profile and((profile.Tower.BestTowerTimes[session.towerId]or 0)/1000)or 0,serverStartTime=session.startTime,towerId=session.towerId,runId=session.runId,completed=session.isFinished,time=session.isFinished and(session.finishTime-session.startTime)or nil})
end)
