--!strict
local Players=game:GetService("Players");local MarketplaceService=game:GetService("MarketplaceService");local RunService=game:GetService("RunService");local ReplicatedStorage=game:GetService("ReplicatedStorage");local Config=require(ReplicatedStorage.Modules.MonetizationConfig);local Profiles=require(script.Parent.Services.PlayerProfileService);local Service=require(script.Parent.Services.MonetizationService);local remotes=require(script.Parent.Services.RemoteService).Ensure();local rate:{[Player]:number}={}
MarketplaceService.ProcessReceipt=function(info)return Service.ProcessReceipt(info)end
local function allowed(p:Player):boolean local now=os.clock();if now-(rate[p] or 0)<1 then return false end;rate[p]=now;return true end
remotes.RequestProductPurchase.OnServerEvent:Connect(function(p,id)if typeof(id)~="string" or not allowed(p) then return end;local product=Config.Products[id];if not product or product.ProductId==0 then remotes.PurchaseResult:FireClient(p,{success=false,message="商品尚未設定"});return end;if not Config.EnableRealPurchases or (RunService:IsStudio() and not Config.AllowStudioPurchasePrompts) then remotes.PurchaseResult:FireClient(p,{success=false,message="真實購買目前停用"});return end;MarketplaceService:PromptProductPurchase(p,product.ProductId)end)
remotes.RequestGamePassPurchase.OnServerEvent:Connect(function(p,id)if typeof(id)~="string" or not allowed(p) then return end;local pass=Config.GamePasses[id];if not pass or pass.GamePassId==0 then remotes.PurchaseResult:FireClient(p,{success=false,message="通行證尚未設定"});return end;if not Config.EnableRealPurchases or (RunService:IsStudio() and not Config.AllowStudioPurchasePrompts) then remotes.PurchaseResult:FireClient(p,{success=false,message="真實購買目前停用"});return end;MarketplaceService:PromptGamePassPurchase(p,pass.GamePassId)end)
Players.PlayerAdded:Connect(function(p)task.spawn(function()local deadline=os.clock()+20;while not Profiles.IsProfileLoaded(p) and os.clock()<deadline do task.wait(.2) end;if Profiles.IsProfileLoaded(p) then Service.CheckPasses(p) end end)end)
for _,p in Players:GetPlayers()do task.spawn(function()local deadline=os.clock()+20;while not Profiles.IsProfileLoaded(p)and os.clock()<deadline do task.wait(.2)end;if Profiles.IsProfileLoaded(p)then Service.CheckPasses(p)end end)end
MarketplaceService.PromptGamePassPurchaseFinished:Connect(function(p,_,purchased)if purchased and Profiles.IsProfileLoaded(p)then task.delay(1,Service.CheckPasses,p)end end)
