--!strict
local RunService=game:GetService("RunService");local ReplicatedStorage=game:GetService("ReplicatedStorage");local Config=require(ReplicatedStorage.Modules.DevelopmentConfig)
if not RunService:IsStudio()or not Config.EnableSmokeTests then return end
local counts={PASS=0,WARN=0,FAIL=0}
local function report(level:string,name:string,detail:any?)counts[level]+=1;local message=string.format("[SmokeTest] %s %s%s",level,name,if detail then ": "..tostring(detail)else "");if level=="FAIL"then warn(message)else print(message)end end
local function test(name:string,fn:()->(boolean,any?))local ok,result,detail=pcall(fn);if not ok then report("FAIL",name,result)elseif result then report("PASS",name)else report("FAIL",name,detail or "check returned false")end end
local function uniqueIds(items:any):(boolean,string?)local seen={};for key,value in items do local id=type(value)=="table"and value.Id or nil;if type(id)~="string"or id==""then return false,"missing Id at "..tostring(key)end;if seen[id]then return false,"duplicate "..id end;seen[id]=true end;return true,nil end
task.defer(function()
	local Maps=require(script.Parent.Services.MapService);local Catalog=require(ReplicatedStorage.Modules.MapCatalog);local TowerConfig=require(ReplicatedStorage.Modules.TowerConfig);local world=workspace:WaitForChild("PartyObbyWorld",10)
	test("MainLobby",function()return world~=nil and world:FindFirstChild("MainLobby")~=nil,"PartyObbyWorld/MainLobby missing"end)
	test("LobbySpawn",function()local lobby=world and world:FindFirstChild("MainLobby");return lobby~=nil and lobby:FindFirstChild("LobbySpawn")~=nil,"LobbySpawn missing"end)
	test("LobbyFacingTarget",function()local lobby=world and world:FindFirstChild("MainLobby");local target=lobby and lobby:FindFirstChild("LobbyFacingTarget");return target~=nil and target:IsA("BasePart")and not target.CanCollide and not target.CanTouch,"LobbyFacingTarget invalid"end)
	test("Portals",function()local lobby=world and world:FindFirstChild("MainLobby");local portals=lobby and lobby:FindFirstChild("Portals");if not portals then return false,"MainLobby.Portals missing"end;local modes=require(ReplicatedStorage.Modules.ModeConfig);for modeId,mode in modes do local portalId=if mode.IsSolo then mode.MapPool[1]else modeId;local found=false;for _,portal in portals:GetChildren()do if portal:GetAttribute("PortalId")==portalId and portal:GetAttribute("ModeId")==modeId and portal:FindFirstChildOfClass("ProximityPrompt")then found=true;break end end;if not found then return false,"missing portal "..portalId end end;return true end)
	test("Lobby visual foundation",function()local lobby=world and world:FindFirstChild("MainLobby");if not lobby then return false,"MainLobby missing"end;local ok,errors=require(script.Parent.Services.LobbyVisualFactory).Validate(lobby);return ok,table.concat(errors,", ")end)
	local remotes=ReplicatedStorage:FindFirstChild("Remotes");for _,name in {"RoundStateChanged","CountdownUpdated","RankingUpdated","PlayerFinished","ResultsUpdated","ModeStateChanged","RequestModeState","SettingsUpdated","TrackPenaltyUpdated"}do test("Remote "..name,function()return remotes~=nil and remotes:FindFirstChild(name)~=nil,name.." missing"end)end
	local raceMaps=0;for id,definition in Catalog do if definition.IsEnabled and definition.Mode=="Race"then raceMaps+=1;test("MapValidation "..id,function()local ok,errors=Maps.ValidateMap(id);return ok,table.concat(errors,", ")end)end end
	test("Three race maps",function()return raceMaps>=3,"found "..raceMaps end)
	for id in TowerConfig do test("MapValidation "..id,function()local ok,errors=Maps.ValidateTower(id);return ok,table.concat(errors,", ")end)end
	for id,definition in TowerConfig do test(id.." obstacle variety",function()local tower=world and world:FindFirstChild("TowerMaps")and world.TowerMaps:FindFirstChild(id);local floors=tower and tower:FindFirstChild("Floors");if not floors then return false,"Floors missing"end;local types={};for index=1,definition.FloorCount do local floor=floors:FindFirstChild(string.format("Floor%02d",index));local kind=floor and floor:GetAttribute("ObstacleType");if type(kind)~="string"or kind==""then return false,"ObstacleType missing at "..index end;types[kind]=true end;local count=0;for _ in types do count+=1 end;return count==definition.FloorCount,"obstacle types are not distinct"end)end
	local PathValidator=require(script.Parent.Services.TowerPathValidator);for id in TowerConfig do test("TowerPath "..id,function()local towerMaps=world and world:FindFirstChild("TowerMaps");local tower=towerMaps and towerMaps:FindFirstChild(id);if not tower then return false,"tower missing"end;local results=PathValidator.Validate(tower);PathValidator.Print(results);return not PathValidator.HasFailures(results),"jump path validation failed"end)end
	for id in TowerConfig do test(id.." required jump clearance",function()local tower=world and world:FindFirstChild("TowerMaps")and world.TowerMaps:FindFirstChild(id);if not tower then return false,"tower missing"end;for _,result in PathValidator.Validate(tower)do if result.Level=="FAIL"and(result.Message:find("blocked by",1,true)or result.Message:find("headroom",1,true))then return false,result.Message end end;return true end);test(id.." no platform overlap",function()local tower=world and world:FindFirstChild("TowerMaps")and world.TowerMaps:FindFirstChild(id);if not tower then return false,"tower missing"end;for _,result in PathValidator.Validate(tower)do if result.Level=="FAIL"and result.Message:find("platform overlap",1,true)then return false,result.Message end end;return true end)end
	local SpawnValidator=require(script.Parent.Services.TowerSpawnService);for id in TowerConfig do test("TowerSpawn "..id,function()local towerMaps=world and world:FindFirstChild("TowerMaps");local tower=towerMaps and towerMaps:FindFirstChild(id);if not tower then return false,"tower missing"end;local ok,errors=SpawnValidator.ValidateTowerSpawn(tower);print(string.format("[TowerValidation] %s %s spawn clearance%s",if ok then "PASS"else"FAIL",id,if #errors>0 then ": "..table.concat(errors,", ")else""));return ok,table.concat(errors,", ")end)end
	for name,module in {QuestConfig=require(ReplicatedStorage.Modules.QuestConfig),AchievementConfig=require(ReplicatedStorage.Modules.AchievementConfig)}do test(name.." unique ids",function()return uniqueIds(module)end)end
	test("ShopConfig unique ids",function()return uniqueIds(require(ReplicatedStorage.Modules.ShopConfig).Items)end)
	test("Rank thresholds",function()local last=-1;for _,tier in require(ReplicatedStorage.Modules.RankConfig).Tiers do if tier.MinimumPoints<=last then return false,"threshold order"end;last=tier.MinimumPoints end;return true end)
	test("AudioId zero safe",function()local audio=require(ReplicatedStorage.Modules.AudioConfig);for _,id in audio.Tracks do if type(id)~="number"or id<0 then return false,"invalid track id"end end;return true end)
	test("Studio memory data",function()return require(script.Parent.Services.DataStoreServiceWrapper).IsMemoryMode(),"DataStore wrapper is not in memory mode"end)
	test("UIStateController required states",function()local required={Lobby=true,Queue=true,MapVote=true,RacePreparing=true,RaceCountdown=true,Racing=true,RaceResults=true,TowerPreparing=true,TowerCountdown=true,TowerRunning=true,TowerResults=true};for _,state in require(ReplicatedStorage.Modules.UIStateConfig).States do required[state]=nil end;return next(required)==nil,"required UI state missing"end)
	test("Tower run schema",function()local config=require(ReplicatedStorage.Modules.TowerRunConfig);local expected={runId=true,towerId=true,player=true,state=true,currentFloor=true,startTime=true,finishTime=true,falls=true,puzzleState=true,lastCheckpointCFrame=true,isFinished=true,rewardGranted=true};for _,field in config.RequiredFields do expected[field]=nil end;return next(expected)==nil,"Tower Run field missing"end)
	test("Tower rewards",function()local rewards=require(ReplicatedStorage.Modules.RewardConfig).Towers;return rewards.Tower01.First==200 and rewards.Tower01.Repeat==80 and rewards.Tower01.PersonalBest==50 and rewards.Tower02.First==300 and rewards.Tower02.Repeat==120 and rewards.Tower02.PersonalBest==75,"tower rewards mismatch"end)
	test("Quest event ids",function()local found={TowerComplete=false,TowerFloor=false,PuzzleMapComplete=false,MapVote=false};for _,quest in require(ReplicatedStorage.Modules.QuestConfig)do if found[quest.ProgressEvent]~=nil then found[quest.ProgressEvent]=true end end;for _,value in found do if not value then return false,"quest event missing"end end;return true end)
	test("Achievement event ids",function()local found={Tower01Complete=false,Tower02Complete=false,TowerNoFalls=false,ClocktowerComplete=false,PuzzleMapComplete=false,AllRaceMaps=false,ComebackWin=false,RankedStreak3=false};for _,achievement in require(ReplicatedStorage.Modules.AchievementConfig)do if found[achievement.Event]~=nil then found[achievement.Event]=true end end;for event,value in found do if not value then return false,"achievement event missing: "..event end end;return true end)
	test("ReturnToLobby cleanup",function()local source=script.Parent.Services.LobbyService;return source~=nil and remotes~=nil and remotes:FindFirstChild("ReturnToLobby")~=nil,"lobby cleanup entrypoint missing"end)
	test("Mobile UI buttons",function()local scripts=game:GetService("StarterPlayer"):FindFirstChild("StarterPlayerScripts");return scripts~=nil and scripts:FindFirstChild("TowerUI")~=nil and scripts:FindFirstChild("ItemUI")~=nil,"TowerUI or ItemUI missing"end)
	print(string.format("[SmokeTest] PASS: %d",counts.PASS));print(string.format("[SmokeTest] WARN: %d",counts.WARN));print(string.format("[SmokeTest] FAIL: %d",counts.FAIL))
end)
