--!strict
local RunService=game:GetService("RunService");local ReplicatedStorage=game:GetService("ReplicatedStorage");local Config=require(ReplicatedStorage.Modules.DevelopmentConfig)
if not RunService:IsStudio()or not Config.EnableSmokeTests then return end
local counts={PASS=0,WARN=0,FAIL=0}
local function report(level:string,name:string,detail:any?)counts[level]+=1;local message=string.format("[SmokeTest] %s %s%s",level,name,if detail then ": "..tostring(detail)else "");if level=="FAIL"then warn(message)else print(message)end end
local function test(name:string,fn:()->(boolean,any?))local ok,result,detail=pcall(fn);if not ok then report("FAIL",name,result)elseif result then report("PASS",name)else report("FAIL",name,detail or "check returned false")end end
local function uniqueIds(items:any):(boolean,string?)local seen={};for key,value in items do local id=type(value)=="table"and value.Id or nil;if type(id)~="string"or id==""then return false,"missing Id at "..tostring(key)end;if seen[id]then return false,"duplicate "..id end;seen[id]=true end;return true,nil end
task.defer(function()
	local Maps=require(script.Parent.Services.MapService);local Catalog=require(ReplicatedStorage.Modules.MapCatalog);local TowerConfig=require(ReplicatedStorage.Modules.TowerConfig);local world=workspace:WaitForChild("PartyObbyWorld",10)
	test("MainLobby",function()return world~=nil and world:FindFirstChild("MainLobby")~=nil,"PartyObbyWorld/MainLobby missing"end)
	test("LobbySpawn",function()local lobby=world and world:FindFirstChild("MainLobby");return lobby~=nil and lobby:FindFirstChild("LobbySpawn")~=nil,"LobbySpawn missing"end)
	test("LobbyFacingTarget",function()local lobby=world and world:FindFirstChild("MainLobby");local target=lobby and lobby:FindFirstChild("LobbyFacingTarget");return target~=nil and target:IsA("BasePart")and not target.CanCollide and not target.CanTouch,"LobbyFacingTarget invalid"end)
	test("Portals",function()local lobby=world and world:FindFirstChild("MainLobby");local portals=lobby and lobby:FindFirstChild("Portals");if not portals then return false,"MainLobby.Portals missing"end;local modes=require(ReplicatedStorage.Modules.ModeConfig);for modeId,mode in modes do local portalId=if mode.IsSolo then mode.MapPool[1]else modeId;local found=false;for _,portal in portals:GetChildren()do if portal:GetAttribute("PortalId")==portalId and portal:GetAttribute("ModeId")==modeId and portal:FindFirstChildOfClass("ProximityPrompt")then found=true;break end end;if not found then return false,"missing portal "..portalId end end;return true end)
	local remotes=ReplicatedStorage:FindFirstChild("Remotes");for _,name in {"RoundStateChanged","CountdownUpdated","RankingUpdated","PlayerFinished","ResultsUpdated","ModeStateChanged","RequestModeState","SettingsUpdated","TrackPenaltyUpdated"}do test("Remote "..name,function()return remotes~=nil and remotes:FindFirstChild(name)~=nil,name.." missing"end)end
	local raceMaps=0;for id,definition in Catalog do if definition.IsEnabled and definition.Mode=="Race"then raceMaps+=1;test("MapValidation "..id,function()local ok,errors=Maps.ValidateMap(id);return ok,table.concat(errors,", ")end)end end
	test("Three race maps",function()return raceMaps>=3,"found "..raceMaps end)
	for id in TowerConfig do test("MapValidation "..id,function()local ok,errors=Maps.ValidateTower(id);return ok,table.concat(errors,", ")end)end
	local PathValidator=require(script.Parent.Services.TowerPathValidator);for id in TowerConfig do test("TowerPath "..id,function()local towerMaps=world and world:FindFirstChild("TowerMaps");local tower=towerMaps and towerMaps:FindFirstChild(id);if not tower then return false,"tower missing"end;local results=PathValidator.Validate(tower);PathValidator.Print(results);return not PathValidator.HasFailures(results),"jump path validation failed"end)end
	for id in TowerConfig do test(id.." required jump clearance",function()local tower=world and world:FindFirstChild("TowerMaps")and world.TowerMaps:FindFirstChild(id);if not tower then return false,"tower missing"end;for _,result in PathValidator.Validate(tower)do if result.Level=="FAIL"and(result.Message:find("blocked by",1,true)or result.Message:find("headroom",1,true))then return false,result.Message end end;return true end);test(id.." no platform overlap",function()local tower=world and world:FindFirstChild("TowerMaps")and world.TowerMaps:FindFirstChild(id);if not tower then return false,"tower missing"end;for _,result in PathValidator.Validate(tower)do if result.Level=="FAIL"and result.Message:find("platform overlap",1,true)then return false,result.Message end end;return true end)end
	local SpawnValidator=require(script.Parent.Services.TowerSpawnService);for id in TowerConfig do test("TowerSpawn "..id,function()local towerMaps=world and world:FindFirstChild("TowerMaps");local tower=towerMaps and towerMaps:FindFirstChild(id);if not tower then return false,"tower missing"end;local ok,errors=SpawnValidator.ValidateTowerSpawn(tower);print(string.format("[TowerValidation] %s %s spawn clearance%s",if ok then "PASS"else"FAIL",id,if #errors>0 then ": "..table.concat(errors,", ")else""));return ok,table.concat(errors,", ")end)end
	for name,module in {QuestConfig=require(ReplicatedStorage.Modules.QuestConfig),AchievementConfig=require(ReplicatedStorage.Modules.AchievementConfig)}do test(name.." unique ids",function()return uniqueIds(module)end)end
	test("ShopConfig unique ids",function()return uniqueIds(require(ReplicatedStorage.Modules.ShopConfig).Items)end)
	test("Rank thresholds",function()local last=-1;for _,tier in require(ReplicatedStorage.Modules.RankConfig).Tiers do if tier.MinimumPoints<=last then return false,"threshold order"end;last=tier.MinimumPoints end;return true end)
	test("AudioId zero safe",function()local audio=require(ReplicatedStorage.Modules.AudioConfig);for _,id in audio.Tracks do if type(id)~="number"or id<0 then return false,"invalid track id"end end;return true end)
	test("Studio memory data",function()return require(script.Parent.Services.DataStoreServiceWrapper).IsMemoryMode(),"DataStore wrapper is not in memory mode"end)
	print(string.format("[SmokeTest] PASS: %d",counts.PASS));print(string.format("[SmokeTest] WARN: %d",counts.WARN));print(string.format("[SmokeTest] FAIL: %d",counts.FAIL))
end)
