--!strict
local Players=game:GetService("Players")
local Profiles=require(script.Parent.Services.PlayerProfileService);local Rewards=require(script.Parent.Services.RewardService);local Leaderboards=require(script.Parent.Services.GlobalLeaderboardService);local Events=require(script.Parent.Services.GameplayEventService);local Tower=require(script.Parent.Services.TowerService);local Lobby=require(script.Parent.Services.LobbyService);local Mode=require(script.Parent.Services.ModeService);local Registry=require(script.Parent.Services.ConnectionRegistry);local remotes=require(script.Parent.Services.RemoteService).Ensure()
local world=workspace:WaitForChild("PartyObbyWorld",10);local maps=world and world:WaitForChild("TowerMaps",10);local bound:{[string]:boolean}={}
local function player(hit:BasePart):Player?local node:Instance?=hit;while node and node~=workspace do if node:IsA("Model")and node:FindFirstChildOfClass("Humanoid")then return Players:GetPlayerFromCharacter(node)end;node=node.Parent end;return nil end
local function bind(map:Folder)
	local id=map.Name;if bound[id]then return end;local floors=map:WaitForChild("Floors",10);local returnPart=map:WaitForChild("ReturnToLobby",10);if not floors or not returnPart then warn("[Tower] incomplete map: "..id);return end;bound[id]=true;local floorCount=#floors:GetChildren()
	for _,floor in floors:GetChildren()do if floor:IsA("BasePart")then Registry.Register(floor.Touched:Connect(function(hit)local p=player(hit);local session=p and Tower.Session(p);local index=floor:GetAttribute("FloorIndex");if p and session and session.towerId==id and session.state=="Running"and typeof(index)=="number"and index==session.currentFloor+1 then session.currentFloor=index;session.floor=index;session.lastCheckpointCFrame=floor.CFrame;session.lastCFrame=floor.CFrame;session.lastSupport=floor;local profile=Profiles.GetProfile(p);if profile then profile.Tower.HighestFloorByTower[id]=math.max(profile.Tower.HighestFloorByTower[id]or 0,index);Profiles.MarkDirty(p)end;local floorCoins=Rewards.TowerFloor(p,session.runId,id,index);Events.Event:Fire(p,"TowerFloor",1);remotes.TowerProgressUpdated:FireClient(p,{state=session.state,floor=index,total=session.floorCount,best=profile and((profile.Tower.BestTowerTimes[id]or 0)/1000)or 0,floorCoins=floorCoins,serverStartTime=session.startTime,towerId=id,runId=session.runId});print(string.format("[Tower] %s reached %s floor %d",p.Name,id,index))end end),"TowerMap:"..id,"Touched")end end
	local finish=map:WaitForChild("TowerFinish",10);if finish and finish:IsA("BasePart")then Registry.Register(finish.Touched:Connect(function(hit)local p=player(hit);local session=p and Tower.Session(p);if not p or not session or session.towerId~=id or session.currentFloor<floorCount or session.state~="Running"or session.rewardGranted then return end;session.state="Finished";session.isFinished=true;session.active=false;session.finishTime=workspace:GetServerTimeNow();local elapsed=session.finishTime-session.startTime;local ms=math.floor(elapsed*1000);local profile=Profiles.GetProfile(p);if not profile then return end;local old=profile.Tower.BestTowerTimes[id]or 0;local first=old==0;local personalBest=first or ms<old;if personalBest then profile.Tower.BestTowerTimes[id]=ms;if id=="Tower01"then Leaderboards.Update(p,"Tower",ms)end end;profile.Tower.TowersCompleted+=1;Profiles.MarkDirty(p);local coins=Rewards.Tower(p,session.runId,id,first,personalBest);session.rewardGranted=true;Events.Event:Fire(p,"TowerComplete",1);Events.Event:Fire(p,id.."Complete",1);if session.falls==0 then Events.Event:Fire(p,"TowerNoFalls",1)end;remotes.ModeStateChanged:FireClient(p,{mode=Mode.Get(p).CurrentMode,inTower=true,uiState="TowerResults",towerId=id});remotes.TowerProgressUpdated:FireClient(p,{state=session.state,completed=true,time=elapsed,best=profile.Tower.BestTowerTimes[id]/1000,coinsEarned=coins,newBest=personalBest,towerId=id,returnIn=10});print(string.format("[Tower] %s completed %s in %.1f seconds",p.Name,id,elapsed));task.delay(10,function()if p.Parent==Players and Tower.Session(p)==session then Lobby.Return(p)end end)end),"TowerMap:"..id,"Touched")end
	local kill=map:WaitForChild("KillFloor",10);if kill and kill:IsA("BasePart")then Registry.Register(kill.Touched:Connect(function(hit)local p=player(hit);local session=p and Tower.Session(p);if p and session and session.towerId==id then Tower.Fall(p,"KillFloor")end end),"TowerMap:"..id,"Touched")end
	local prompt=returnPart:FindFirstChildOfClass("ProximityPrompt");if prompt then Registry.Register(prompt.Triggered:Connect(function(p)if Tower.Session(p)then Lobby.Return(p)end end),"TowerMap:"..id,"Prompt")end
end
if maps then for _,map in maps:GetChildren()do if map:IsA("Folder")then task.spawn(bind,map)end end;Registry.Register(maps.ChildAdded:Connect(function(map)if map:IsA("Folder")then task.spawn(bind,map)end end),"TowerService","ChildAdded")end
local function watch(p:Player)Registry.Register(p.CharacterAdded:Connect(function()if Tower.Session(p)then task.delay(.2,function()if Tower.Session(p)then Tower.Fall(p,"CharacterRespawn")end end)end end),"TowerPlayer:"..p.UserId,"CharacterAdded")end
Registry.Register(Players.PlayerAdded:Connect(watch),"TowerService","PlayerAdded");for _,p in Players:GetPlayers()do watch(p)end
Registry.Register(Players.PlayerRemoving:Connect(function(p)Tower.Leave(p);Registry.DisconnectOwner("TowerPlayer:"..p.UserId)end),"TowerService","PlayerRemoving")
