--!strict
local Players=game:GetService("Players")
local Profiles=require(script.Parent.Services.PlayerProfileService);local Rewards=require(script.Parent.Services.RewardService);local Leaderboards=require(script.Parent.Services.GlobalLeaderboardService);local Events=require(script.Parent.Services.GameplayEventService);local Tower=require(script.Parent.Services.TowerService);local Lobby=require(script.Parent.Services.LobbyService);local Registry=require(script.Parent.Services.ConnectionRegistry);local remotes=require(script.Parent.Services.RemoteService).Ensure()
local world=workspace:WaitForChild("PartyObbyWorld",10);local maps=world and world:WaitForChild("TowerMaps",10);local bound:{[string]:boolean}={}
local function player(hit:BasePart):Player?local node:Instance?=hit;while node and node~=workspace do if node:IsA("Model")and node:FindFirstChildOfClass("Humanoid")then return Players:GetPlayerFromCharacter(node)end;node=node.Parent end;return nil end
local function bind(map:Folder)
	local id=map.Name;if bound[id]then return end;local floors=map:WaitForChild("Floors",10);local returnPart=map:WaitForChild("ReturnToLobby",10);if not floors or not returnPart then warn("[Tower] incomplete map: "..id);return end;bound[id]=true;local floorCount=#floors:GetChildren()
	for _,floor in floors:GetChildren()do if floor:IsA("BasePart")then Registry.Register(floor.Touched:Connect(function(hit)local p=player(hit);local session=p and Tower.Session(p);local index=floor:GetAttribute("FloorIndex");if p and session and session.mapId==id and session.active and typeof(index)=="number"and index==session.floor+1 then session.floor=index;session.lastCFrame=floor.CFrame;session.lastSupport=floor;local profile=Profiles.GetProfile(p);if profile then profile.Tower.HighestFloorByTower[id]=math.max(profile.Tower.HighestFloorByTower[id]or 0,index);Profiles.MarkDirty(p)end;remotes.TowerProgressUpdated:FireClient(p,{floor=index,total=session.floorCount,best=profile and((profile.Tower.BestTowerTimes[id]or 0)/1000)or 0,towerId=id});print(string.format("[Tower] %s reached %s floor %d",p.Name,id,index))end end),"TowerMap:"..id,"Touched")end end
	local finish=map:WaitForChild("TowerFinish",10);if finish and finish:IsA("BasePart")then Registry.Register(finish.Touched:Connect(function(hit)local p=player(hit);local session=p and Tower.Session(p);if not p or not session or session.mapId~=id or session.floor<floorCount or not session.active then return end;session.active=false;local elapsed=os.clock()-session.started;local ms=math.floor(elapsed*1000);local profile=Profiles.GetProfile(p);if not profile then return end;local old=profile.Tower.BestTowerTimes[id]or 0;local first=old==0;local personalBest=first or ms<old;if personalBest then profile.Tower.BestTowerTimes[id]=ms;if id=="Tower01"then Leaderboards.Update(p,"Tower",ms)end end;profile.Tower.TowersCompleted+=1;Profiles.MarkDirty(p);local coins=Rewards.Tower(p,session.runId,first,personalBest);Events.Event:Fire(p,"TowerComplete",1);if session.falls==0 then Events.Event:Fire(p,"TowerNoFalls",1)end;if id=="Tower02"then Events.Event:Fire(p,"Tower02Complete",1)end;remotes.TowerProgressUpdated:FireClient(p,{completed=true,time=elapsed,best=profile.Tower.BestTowerTimes[id]/1000,coinsEarned=coins,towerId=id});print(string.format("[Tower] %s completed %s in %.1f seconds",p.Name,id,elapsed));Tower.Leave(p);task.delay(10,function()if p.Parent==Players then Lobby.Return(p)end end)end),"TowerMap:"..id,"Touched")end
	local kill=map:WaitForChild("KillFloor",10);if kill and kill:IsA("BasePart")then Registry.Register(kill.Touched:Connect(function(hit)local p=player(hit);local session=p and Tower.Session(p);if p and session and session.mapId==id then session.falls+=1;Profiles.IncrementValue(p,"Tower.TotalFalls",1);Tower.Respawn(p)end end),"TowerMap:"..id,"Touched")end
	local prompt=returnPart:FindFirstChildOfClass("ProximityPrompt");if prompt then Registry.Register(prompt.Triggered:Connect(function(p)if Tower.Session(p)then Lobby.Return(p)end end),"TowerMap:"..id,"Prompt")end
end
if maps then for _,map in maps:GetChildren()do if map:IsA("Folder")then task.spawn(bind,map)end end;Registry.Register(maps.ChildAdded:Connect(function(map)if map:IsA("Folder")then task.spawn(bind,map)end end),"TowerService","ChildAdded")end
Registry.Register(Players.PlayerAdded:Connect(function(p)Registry.Register(p.CharacterAdded:Connect(function()if Tower.Session(p)then task.defer(function()Tower.Respawn(p)end)end end),"TowerPlayer:"..p.UserId,"CharacterAdded")end),"TowerService","PlayerAdded")
for _,p in Players:GetPlayers()do Registry.Register(p.CharacterAdded:Connect(function()if Tower.Session(p)then task.defer(function()Tower.Respawn(p)end)end end),"TowerPlayer:"..p.UserId,"CharacterAdded")end
