--!strict
local Players=game:GetService("Players");local TweenService=game:GetService("TweenService");local Profiles=require(script.Parent.Services.PlayerProfileService);local Rewards=require(script.Parent.Services.RewardService);local Leaderboards=require(script.Parent.Services.GlobalLeaderboardService);local Events=require(script.Parent.Services.GameplayEventService);local Tower=require(script.Parent.Services.TowerService);local Lobby=require(script.Parent.Services.LobbyService);local remotes=require(script.Parent.Services.RemoteService).Ensure();local world=workspace:WaitForChild("PartyObbyWorld",10);local map=world and world.TowerMaps:WaitForChild("Tower01",10)
local function player(hit:BasePart):Player? local n:Instance?=hit;while n and n~=workspace do if n:IsA("Model") and n:FindFirstChildOfClass("Humanoid") then return Players:GetPlayerFromCharacter(n) end;n=n.Parent end;return nil end
if map then
	for _,floor in map.Floors:GetChildren() do if floor:IsA("BasePart") then floor.Touched:Connect(function(hit) local p=player(hit);local s=p and Tower.Session(p);local index=floor:GetAttribute("TowerFloor");if p and s and s.active and typeof(index)=="number" and index==s.floor+1 then s.floor=index;s.lastCFrame=floor.CFrame;local profile=Profiles.GetProfile(p);if profile then profile.Tower.HighestFloorByTower.Tower01=math.max(profile.Tower.HighestFloorByTower.Tower01 or 0,index);Profiles.MarkDirty(p) end;remotes.TowerProgressUpdated:FireClient(p,{floor=index,total=10,best=profile and ((profile.Tower.BestTowerTimes.Tower01 or 0)/1000) or 0});print(string.format("[Tower] %s reached floor %d",p.Name,index)) end end) end end
	for _,floor in map.Floors:GetChildren() do if floor:IsA("BasePart") and floor:GetAttribute("MovingPlatform") then TweenService:Create(floor,TweenInfo.new(2.5,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,-1,true),{Position=floor.Position+Vector3.new(10,0,0)}):Play() elseif floor:IsA("BasePart") and floor:GetAttribute("DisappearPlatform") then floor.Touched:Connect(function()if floor.Transparency==0 then task.delay(.4,function()floor.Transparency=1;floor.CanCollide=false;task.wait(2);floor.Transparency=0;floor.CanCollide=true end) end end) end end
	local puzzles=map:FindFirstChild("Puzzles");if puzzles then local box=puzzles:FindFirstChild("PushBox")::BasePart?;local plate=puzzles:FindFirstChild("PressurePlate")::BasePart?;local door6=puzzles:FindFirstChild("PuzzleDoor06")::BasePart?;if box and plate and door6 then local origin=box.CFrame;plate.Touched:Connect(function(hit)if hit==box then door6.CanCollide=false;door6.Transparency=.7 end end);local reset=puzzles:FindFirstChild("ResetPuzzle");local prompt=reset and reset:FindFirstChildOfClass("ProximityPrompt");if prompt then prompt.Triggered:Connect(function(p)if Tower.Session(p) then box.CFrame=origin;box.AssemblyLinearVelocity=Vector3.zero;door6.CanCollide=true;door6.Transparency=0 end end) end end;local buttons=puzzles:FindFirstChild("SequenceButtons");local door7=puzzles:FindFirstChild("PuzzleDoor07")::BasePart?;local expected:{[Player]:number}={};if buttons and door7 then for _,button in buttons:GetChildren() do if button:IsA("BasePart") then button.Touched:Connect(function(hit)local p=player(hit);if not p or not Tower.Session(p) then return end;local index=button:GetAttribute("SequenceIndex");local want=expected[p] or 1;if index==want then expected[p]=want+1;if want==3 then door7.CanCollide=false;door7.Transparency=.7;remotes.ItemMessage:FireClient(p,"順序正確！門已開啟") end else expected[p]=1;remotes.ItemMessage:FireClient(p,"順序錯誤，請重新開始") end end) end end end end
	map.TowerFinish.Touched:Connect(function(hit)local p=player(hit);local s=p and Tower.Session(p);if not p or not s or s.floor<10 or not s.active then return end;s.active=false;local elapsed=os.clock()-s.started;local ms=math.floor(elapsed*1000);local profile=Profiles.GetProfile(p);if not profile then return end;local old=profile.Tower.BestTowerTimes.Tower01 or 0;local first=old==0;local personalBest=first or ms<old;if personalBest then profile.Tower.BestTowerTimes.Tower01=ms;Leaderboards.Update(p,"Tower",ms) end;profile.Tower.TowersCompleted+=1;Profiles.MarkDirty(p);local coins=Rewards.Tower(p,s.runId,first,personalBest);Events.Event:Fire(p,"TowerComplete",1);remotes.TowerProgressUpdated:FireClient(p,{completed=true,time=elapsed,best=profile.Tower.BestTowerTimes.Tower01/1000,coinsEarned=coins});print(string.format("[Tower] %s completed Tower01 in %.1f seconds",p.Name,elapsed));Tower.Leave(p);task.delay(10,function()if p.Parent==Players then Lobby.Return(p) end end)end)
	map.KillFloor.Touched:Connect(function(hit)local p=player(hit);local s=p and Tower.Session(p);if p and s then Profiles.IncrementValue(p,"Tower.TotalFalls",1);require(script.Parent.Services.RaceService).Teleport(p,s.lastCFrame,8)end end)
end
