--!strict
local RunService=game:GetService("RunService");local Players=game:GetService("Players");local Tower=require(script.Parent.Services.TowerService);local Registry=require(script.Parent.Services.ConnectionRegistry)
local world=workspace:WaitForChild("PartyObbyWorld",10);local maps=world and world:WaitForChild("TowerMaps",10);if not maps then return end
local rotating:{BasePart}={}
local function player(hit:BasePart):Player?local node:Instance?=hit;while node and node~=workspace do if node:IsA("Model")and node:FindFirstChildOfClass("Humanoid")then return Players:GetPlayerFromCharacter(node)end;node=node.Parent end;return nil end
local function marker(parent:Instance,name:string,position:Vector3,text:string,color:Color3):BasePart local part=Instance.new("Part");part.Name=name;part.Size=Vector3.new(4,1,4);part.Position=position;part.Anchored=true;part.CanCollide=false;part.CanTouch=false;part.Color=color;part.Material=Enum.Material.Neon;part:SetAttribute("DecorativeObject",true);part.Parent=parent;local gui=Instance.new("BillboardGui");gui.Size=UDim2.fromOffset(150,45);gui.StudsOffset=Vector3.new(0,3,0);gui.AlwaysOnTop=true;gui.Parent=part;local label=Instance.new("TextLabel");label.Size=UDim2.fromScale(1,1);label.BackgroundTransparency=1;label.Text=text;label.TextScaled=true;label.TextColor3=Color3.new(1,1,1);label.TextStrokeTransparency=.2;label.Parent=gui;return part end
local function bind(tower:Folder)
	while tower:GetAttribute("PathValidationReady")~=true do task.wait(.1)end;local floors=tower:WaitForChild("Floors");local owner="TowerObstacles:"..tower.Name;local effects=tower:FindFirstChild("ObstacleEffects")or Instance.new("Folder");effects.Name="ObstacleEffects";effects.Parent=tower
	for index=1,#floors:GetChildren()do local floor=floors:FindFirstChild(string.format("Floor%02d",index));if floor and floor:IsA("BasePart")then marker(effects,"FloorMarker"..index,floor.Position+Vector3.new(0,floor.Size.Y/2+.6,0),string.format("%s　FLOOR %02d",if index<#floors:GetChildren()then"➜"else"★",index),floor.Color)end end
	local spinnerIndex=if tower.Name=="Tower01"then 3 else 4;local spinnerFloor=floors:FindFirstChild(string.format("Floor%02d",spinnerIndex));if spinnerFloor and spinnerFloor:IsA("BasePart")then local beam=Instance.new("Part");beam.Name="SafeSpinner";beam.Size=Vector3.new(14,1,2);beam.CFrame=spinnerFloor.CFrame*CFrame.new(0,3,0);beam.Anchored=true;beam.CanCollide=false;beam.CanTouch=true;beam.Color=Color3.fromRGB(245,110,75);beam.Material=Enum.Material.Neon;beam.Parent=effects;table.insert(rotating,beam);Registry.Register(beam.Touched:Connect(function(hit)local p=player(hit);local session=p and Tower.Session(p);local root=p and p.Character and p.Character:FindFirstChild("HumanoidRootPart");if session and session.towerId==tower.Name and root and root:IsA("BasePart")then root.AssemblyLinearVelocity+=beam.CFrame.RightVector*10 end end),owner,"Touched")end
	local disappearIndex=if tower.Name=="Tower01"then 4 else 5;local disappearFloor=floors:FindFirstChild(string.format("Floor%02d",disappearIndex));local nodes=disappearFloor and disappearFloor:FindFirstChild("JumpNodes");local node=nodes and nodes:FindFirstChild("JumpNode02");local value=node and node:FindFirstChild("TargetPlatform");local platform=if value and value:IsA("ObjectValue")then value.Value else nil;if platform and platform:IsA("BasePart")then local busy=false;Registry.Register(platform.Touched:Connect(function(hit)if busy or not player(hit)then return end;busy=true;platform.Color=Color3.fromRGB(255,190,70);task.delay(1,function()platform.Transparency=.7;platform.CanCollide=false;task.delay(2.5,function()if platform.Parent then platform.Transparency=0;platform.CanCollide=true;platform.Color=Color3.fromRGB(185,145,95)end;busy=false end)end)end),owner,"Touched")end
	local hazardIndex=if tower.Name=="Tower01"then 5 else 10;local hazardFloor=floors:FindFirstChild(string.format("Floor%02d",hazardIndex));if hazardFloor and hazardFloor:IsA("BasePart")then local zone=Instance.new("Part");zone.Name=if tower.Name=="Tower01"then"WindZone"else"SafeLightWall";zone.Size=Vector3.new(8,6,3);zone.CFrame=hazardFloor.CFrame*CFrame.new(0,4,0);zone.Anchored=true;zone.CanCollide=false;zone.CanTouch=true;zone.Transparency=if tower.Name=="Tower01"then .8 else .35;zone.Color=Color3.fromRGB(100,210,255);zone.Material=Enum.Material.Neon;zone.Parent=effects;Registry.Register(zone.Touched:Connect(function(hit)local p=player(hit);local session=p and Tower.Session(p);local root=p and p.Character and p.Character:FindFirstChild("HumanoidRootPart");if not session or session.towerId~=tower.Name then return end;if tower.Name=="Tower01"and root and root:IsA("BasePart")then root.AssemblyLinearVelocity+=Vector3.new(9,0,0)else Tower.Fall(p,"SafeLightWall")end end),owner,"Touched")end
end
for _,tower in maps:GetChildren()do if tower:IsA("Folder")then task.spawn(bind,tower)end end
Registry.Register(RunService.Heartbeat:Connect(function(delta)for i=#rotating,1,-1 do local beam=rotating[i];if beam.Parent then beam.CFrame*=CFrame.Angles(0,math.rad(45)*delta,0)else table.remove(rotating,i)end end end),"TowerObstacleService","Heartbeat")
