--!strict
if workspace:FindFirstChild("PartyObbyWorld") then return end
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local TowerJumpConfig=require(ReplicatedStorage.Modules.TowerJumpConfig)
local world=Instance.new("Folder");world.Name="PartyObbyWorld";world.Parent=workspace
local lobby=Instance.new("Folder");lobby.Name="MainLobby";lobby.Parent=world
local raceMaps=Instance.new("Folder");raceMaps.Name="RaceMaps";raceMaps.Parent=world
local raceReference=Instance.new("Folder");raceReference.Name="VillageRace01";raceReference:SetAttribute("RuntimeMapName","PartyObbyMap");raceReference.Parent=raceMaps
local towerMaps=Instance.new("Folder");towerMaps.Name="TowerMaps";towerMaps.Parent=world
local runtime=Instance.new("Folder");runtime.Name="Runtime";runtime.Parent=world;for _,n in {"ActiveMatches","ActiveItems","TemporaryEffects"} do local f=Instance.new("Folder");f.Name=n;f.Parent=runtime end
local function part(name:string,size:Vector3,position:Vector3,color:Color3,parent:Instance?,collide:boolean?):Part local p=Instance.new("Part");p.Name=name;p.Size=size;p.Position=position;p.Color=color;p.Anchored=true;p.CanCollide=collide~=false;p.Parent=parent or lobby;return p end
local function jumpNode(folder:Instance,order:number,target:BasePart)
	local node=part(string.format("JumpNode%02d",order),Vector3.new(1,1,1),target.Position+Vector3.new(0,target.Size.Y*.5+.5,0),Color3.fromRGB(80,220,255),folder,false)
	node.Transparency=1;node.CanQuery=false;node.CanTouch=false;node:SetAttribute("JumpOrder",order);node:SetAttribute("RequiredPath",true)
	local targetValue=Instance.new("ObjectValue");targetValue.Name="TargetPlatform";targetValue.Value=target;targetValue.Parent=node
end
local function label(p:BasePart,text:string) local g=Instance.new("BillboardGui");g.Size=UDim2.fromScale(7,1.5);g.StudsOffset=Vector3.new(0,4,0);g.AlwaysOnTop=true;g.Parent=p;local t=Instance.new("TextLabel");t.Size=UDim2.fromScale(1,1);t.BackgroundTransparency=1;t.Text=text;t.TextScaled=true;t.TextColor3=Color3.new(1,1,1);t.TextStrokeTransparency=.2;t.Font=Enum.Font.GothamBold;t.Parent=g end
local center=Vector3.new(-300,5,0);local plaza=part("Plaza",Vector3.new(100,1,100),center,Color3.fromRGB(190,170,130));plaza.Material=Enum.Material.Cobblestone
local spawn=part("LobbySpawn",Vector3.new(12,1,12),center+Vector3.new(0,1,-30),Color3.fromRGB(75,210,130));label(spawn,"爆笑村莊廣場")
local facingTarget=part("LobbyFacingTarget",Vector3.new(1,1,1),center+Vector3.new(0,1,0),Color3.new(1,1,1),lobby,false);facingTarget.CanTouch=false;facingTarget.CanQuery=true;facingTarget.Transparency=1;spawn.CFrame=CFrame.lookAt(spawn.Position,Vector3.new(facingTarget.Position.X,spawn.Position.Y,facingTarget.Position.Z))
local receive=part("ReturnReceiver",Vector3.new(18,1,12),center+Vector3.new(0,1,-40),Color3.fromRGB(90,180,255));receive.Transparency=.4
local decor=Instance.new("Folder");decor.Name="Decorations";decor.Parent=lobby
local fountain=part("VillageFountain",Vector3.new(14,3,14),center+Vector3.new(0,2,0),Color3.fromRGB(80,175,240),decor);fountain.Shape=Enum.PartType.Cylinder
local portals=Instance.new("Folder");portals.Name="Portals";portals.Parent=lobby
local portalData={{"CasualRacePortal","多人休閒競速\n2～8 人・派對道具",-36,"CasualRace","CasualRace",nil},{"RankedRacePortal","多人排位競速\n影響逃亡積分",-12,"RankedRace","RankedRace",nil},{"Tower01Portal","單人爬塔\n失控村莊瞭望塔",12,"Tower01","SoloTower","Tower01"},{"Tower02Portal","單人機關高塔\n十二層機關",36,"Tower02","SoloTower02","Tower02"}}
for _,d in portalData do local p=part(d[1],Vector3.new(18,10,3),center+Vector3.new(d[3],5,28),d[5]=="RankedRace"and Color3.fromRGB(245,185,55)or Color3.fromRGB(100,190,245),portals);p.Material=Enum.Material.Neon;label(p,d[2]);p:SetAttribute("PortalId",d[4]);p:SetAttribute("DisplayName",d[2]);p:SetAttribute("ModeId",d[5]);p:SetAttribute("TowerId",d[6]);p:SetAttribute("IsEnabled",true);local prompt=Instance.new("ProximityPrompt");prompt.ActionText="選擇模式";prompt.ObjectText=d[2];prompt.HoldDuration=.2;prompt.MaxActivationDistance=12;prompt.KeyboardKeyCode=Enum.KeyCode.E;prompt.GamepadKeyCode=Enum.KeyCode.ButtonX;prompt.Parent=p end
for i,d in ipairs({{"ShopPortal","商店即將開放"},{"RankDisplay","牌位展示區"},{"DailyQuestArea","每日任務・即將開放"},{"PracticeArea","練習區"}}) do local p=part(d[1],Vector3.new(12,7,3),center+Vector3.new(-45+(i-1)*30,4,-5),Color3.fromRGB(150,105,70));label(p,d[2]) end
for i=1,8 do local prop=part("VillageProp"..i,Vector3.new(3,4,3),center+Vector3.new(-45+(i%4)*30,2,-45+math.floor(i/4)*85),i%2==0 and Color3.fromRGB(235,185,60) or Color3.fromRGB(125,75,40),decor,false);prop:SetAttribute("DecorativeObject",true) end
local tower=Instance.new("Folder");tower.Name="Tower01";tower.Parent=towerMaps
local base=Vector3.new(300,5,0);local towerStart=part("TowerStart",Vector3.new(16,1,16),base,Color3.fromRGB(80,200,130),tower);label(towerStart,"失控村莊瞭望塔")
local checkpoints=Instance.new("Folder");checkpoints.Name="Floors";checkpoints.Parent=tower
for i=1,10 do local target=base+Vector3.new((i%2==0 and 8 or -8),i*10,0);local floor=part(string.format("Floor%02d",i),Vector3.new(14-(i%3)*2,1,14-(i%2)*3),target,Color3.fromHSV(i/10,.7,1),checkpoints);floor:SetAttribute("FloorIndex",i);floor:SetAttribute("FloorCheckpoint",true);floor:SetAttribute("IsTowerPlatform",true);if i==2 or i==9 then floor:SetAttribute("MovingPlatform",true) elseif i==4 then floor:SetAttribute("DisappearPlatform",true) elseif i==6 then floor:SetAttribute("PushBoxPuzzle",true) elseif i==7 then floor:SetAttribute("SequencePuzzle",true) end;local previous=if i==1 then base else base+Vector3.new(((i-1)%2==0 and 8 or -8),(i-1)*10,0);local nodes=Instance.new("Folder");nodes.Name="JumpNodes";nodes.Parent=floor;for step=1,2 do local alpha=step/3;local platform=part(string.format("Step%02d_%d",i,step),Vector3.new(TowerJumpConfig.MinimumPlatformWidth,1,TowerJumpConfig.MinimumPlatformDepth),previous:Lerp(target,alpha),Color3.fromRGB(185,145,95),tower);platform:SetAttribute("IsTowerPlatform",true);jumpNode(nodes,step,platform) end;jumpNode(nodes,3,floor) end
local puzzles=Instance.new("Folder");puzzles.Name="Puzzles";puzzles.Parent=tower
local box=part("PushBox",Vector3.new(4,4,4),base+Vector3.new(-8,63,0),Color3.fromRGB(135,85,45),puzzles);box.Anchored=false;local plate=part("PressurePlate",Vector3.new(6,.5,6),base+Vector3.new(3,60.8,0),Color3.fromRGB(80,210,100),puzzles);plate:SetAttribute("Puzzle","PushBox");local door=part("PuzzleDoor06",Vector3.new(12,10,1),base+Vector3.new(0,66,8),Color3.fromRGB(175,75,55),puzzles)
local reset=part("ResetPuzzle",Vector3.new(4,4,2),base+Vector3.new(-14,63,0),Color3.fromRGB(220,85,70),puzzles);local resetPrompt=Instance.new("ProximityPrompt");resetPrompt.ActionText="重置木箱";resetPrompt.ObjectText="推箱機關";resetPrompt.Parent=reset
local buttons=Instance.new("Folder");buttons.Name="SequenceButtons";buttons.Parent=puzzles;for i=1,3 do local b=part("Button"..i,Vector3.new(3,.5,3),base+Vector3.new(-6+i*6,70.8,-3),Color3.fromRGB(245,185,55),buttons);b:SetAttribute("SequenceIndex",i) end;part("PuzzleDoor07",Vector3.new(12,10,1),base+Vector3.new(0,76,8),Color3.fromRGB(175,75,55),puzzles)
local finishPlatform=part("FinishPlatform",Vector3.new(16,4,16),base+Vector3.new(0,112,0),Color3.fromRGB(255,220,60),tower);local finish=part("TowerFinish",Vector3.new(14,8,14),finishPlatform.Position+Vector3.new(0,6,0),Color3.fromRGB(255,220,60),tower,false);finish.Transparency=1;finish.CanTouch=true;finish.CanQuery=false;finish:SetAttribute("IgnoreTowerPathValidation",true);local finishDecoration=part("FinishDecoration",Vector3.new(2,6,2),finishPlatform.Position+Vector3.new(0,6,10),Color3.fromRGB(255,220,60),tower,false);finishDecoration:SetAttribute("DecorativeObject",true);finishDecoration:SetAttribute("IgnoreTowerPathValidation",true);label(finishDecoration,"TOWER FINISH")
part("KillFloor",Vector3.new(90,1,90),base+Vector3.new(0,-15,0),Color3.fromRGB(220,65,65),tower)
local return1=part("ReturnToLobby",Vector3.new(7,1,7),base+Vector3.new(22,1,0),Color3.fromRGB(90,180,255),tower);local returnPrompt1=Instance.new("ProximityPrompt");returnPrompt1.ActionText="返回大廳";returnPrompt1.GamepadKeyCode=Enum.KeyCode.ButtonX;returnPrompt1.Parent=return1
local tower2=Instance.new("Folder");tower2.Name="Tower02";tower2:SetAttribute("MapId","Tower02");tower2:SetAttribute("Mode","Tower");tower2:SetAttribute("MapVersion",1);tower2.Parent=towerMaps;local base2=Vector3.new(450,5,0);local start2=part("TowerStart",Vector3.new(16,1,16),base2,Color3.fromRGB(80,190,150),tower2);label(start2,"村長的機關高塔");local floors2=Instance.new("Folder");floors2.Name="Floors";floors2.Parent=tower2;for i=1,12 do local target=base2+Vector3.new(i%2==0 and 9 or -9,i*9,0);local floor=part(string.format("Floor%02d",i),Vector3.new(11,1,11),target,Color3.fromHSV(i/12,.7,1),floors2);floor:SetAttribute("FloorIndex",i);floor:SetAttribute("FloorCheckpoint",true);floor:SetAttribute("ObstacleType",({"Jump","Moving","Spinner","Disappear","Wind","ColorSequence","PushBox","Maze","Elevator","LightWall","Pendulum","Final"})[i]);local previous=if i==1 then base2 else base2+Vector3.new((i-1)%2==0 and 9 or -9,(i-1)*9,0);for step=1,2 do part(string.format("Tower02Step%02d_%d",i,step),Vector3.new(5,1,5),previous:Lerp(target,step/3),Color3.fromRGB(165,125,95),tower2)end end;local finish2=part("TowerFinish",Vector3.new(16,1,16),base2+Vector3.new(0,118,0),Color3.fromRGB(255,215,65),tower2);label(finish2,"TOWER02 FINISH");part("KillFloor",Vector3.new(100,1,100),base2+Vector3.new(0,-15,0),Color3.fromRGB(220,65,65),tower2);local return2=part("ReturnToLobby",Vector3.new(7,1,7),base2+Vector3.new(22,1,0),Color3.fromRGB(90,180,255),tower2);local returnPrompt2=Instance.new("ProximityPrompt");returnPrompt2.ActionText="返回大廳";returnPrompt2.GamepadKeyCode=Enum.KeyCode.ButtonX;returnPrompt2.Parent=return2
finish2.Name="FinishPlatform";finish2.Size=Vector3.new(16,4,16);finish2:SetAttribute("IsTowerPlatform",true);finish2:SetAttribute("PlatformType","Finish");local towerFinish2=part("TowerFinish",Vector3.new(14,8,14),finish2.Position+Vector3.new(0,6,0),Color3.fromRGB(255,215,65),tower2,false);towerFinish2.Transparency=1;towerFinish2.CanTouch=true;towerFinish2.CanQuery=false;towerFinish2:SetAttribute("IgnoreTowerPathValidation",true);local decoration2=part("FinishDecoration",Vector3.new(2,6,2),finish2.Position+Vector3.new(0,6,10),Color3.fromRGB(255,215,65),tower2,false);decoration2:SetAttribute("DecorativeObject",true);decoration2:SetAttribute("IgnoreTowerPathValidation",true);local oldLabel=finish2:FindFirstChildOfClass("BillboardGui");if oldLabel then oldLabel.Parent=decoration2 end
