--!strict
local Service={}
local function part(parent:Instance,name:string,size:Vector3,cf:CFrame,color:Color3,collide:boolean?):Part local p=Instance.new("Part");p.Name=name;p.Size=size;p.CFrame=cf;p.Color=color;p.Anchored=true;p.CanCollide=collide~=false;p.Parent=parent;return p end
local function baseMap(id:string,checkpointCount:number,origin:Vector3):Folder local map=Instance.new("Folder");map.Name=id;map:SetAttribute("MapId",id);map:SetAttribute("Mode","Race");map:SetAttribute("MapVersion",1);local starts=Instance.new("Folder");starts.Name="RaceStartSpawns";starts.Parent=map;local direction=part(map,"StartDirection",Vector3.one,CFrame.new(origin+Vector3.new(0,5,20)),Color3.new(1,1,1),false);direction.Transparency=1;direction.CanTouch=false;for i=1,8 do local x=-10+((i-1)%4)*6;local z=math.floor((i-1)/4)*6;local pos=origin+Vector3.new(x,2,z);part(starts,string.format("StartSpawn%02d",i),Vector3.new(5,1,5),CFrame.lookAt(pos,Vector3.new(origin.X,pos.Y,origin.Z+20)),Color3.fromRGB(80,170,250))end;local cps=Instance.new("Folder");cps.Name="Checkpoints";cps.Parent=map;for i=1,checkpointCount do local z=i*55;local y=if id=="ClocktowerEscape02" then i*18 else 5;local cp=part(cps,string.format("Checkpoint%02d",i),Vector3.new(30,10,3),CFrame.new(origin+Vector3.new(0,y,z)),Color3.fromRGB(70,230,180),false);cp.Transparency=.6;cp.CanTouch=true;cp:SetAttribute("CheckpointIndex",i)end;local finalY=if id=="ClocktowerEscape02" then checkpointCount*18 else 5;local finish=part(map,"FinishLine",Vector3.new(30,1,8),CFrame.new(origin+Vector3.new(0,finalY,checkpointCount*55+45)),Color3.fromRGB(255,220,60),false);finish.CanTouch=true;part(map,"FinishWaitingArea",Vector3.new(30,1,18),finish.CFrame*CFrame.new(0,0,-15),Color3.fromRGB(80,200,110));local kill=part(map,"KillFloor",Vector3.new(180,1,checkpointCount*70+120),CFrame.new(origin+Vector3.new(0,-20,(checkpointCount*55)/2)),Color3.fromRGB(220,60,60));kill.Transparency=.4;local tracks=Instance.new("Folder");tracks.Name="TrackSurfaces";tracks.Parent=map;return map end
function Service.Build(id:string):Folder
	if id=="VillageRace01"then local source=workspace:FindFirstChild("PartyObbyMap");if source and source:IsA("Folder")then local copy=source:Clone();copy.Name=id;copy:SetAttribute("MapId",id);copy:SetAttribute("Mode","Race");copy:SetAttribute("MapVersion",2);return copy end end
	local count=if id=="ClocktowerEscape02" then 4 else 3;local map=baseMap(id,count,Vector3.zero);local tracks=map.TrackSurfaces;local boxes=Instance.new("Folder");boxes.Name="ItemBoxes";boxes.Parent=map;for i=1,5 do local box=part(boxes,"MysteryBox"..i,Vector3.new(4,4,4),CFrame.new((i%2==0 and 7 or -7),8,i*40),Color3.fromHSV(i/5,.8,1),false);box.Material=Enum.Material.Neon;box.Transparency=.2;box.CanTouch=true end
	if id=="ClocktowerEscape02" then for i=0,16 do local y=math.floor(i/4)*18;local x=(i%2==0 and -8 or 8);local p=part(tracks,"RoofPlatform"..i,Vector3.new(16,2,14),CFrame.new(x,y+1,i*14),Color3.fromRGB(105,115,145));p:SetAttribute("RaceTrackSurface",true)end;for i=1,5 do local gear=part(map,"Gear"..i,Vector3.new(16,1,3),CFrame.new(0,15+i*13,45+i*28),Color3.fromRGB(180,130,70));gear:SetAttribute("MovingObstacle",true)end
	else for i=0,14 do local p=part(tracks,"WorkshopRoad"..i,Vector3.new(26,1,18),CFrame.new(0,4,i*18),Color3.fromRGB(175,130,85));p:SetAttribute("RaceTrackSurface",true)end;local puzzles=Instance.new("Folder");puzzles.Name="Puzzles";puzzles.Parent=map;for i,color in ipairs({Color3.fromRGB(230,70,70),Color3.fromRGB(70,210,90),Color3.fromRGB(70,120,240)})do local b=part(puzzles,"ColorButton"..i,Vector3.new(5,.5,5),CFrame.new(-7+i*7,5,85),color);b:SetAttribute("PuzzleId","ColorDoor");b:SetAttribute("Step",i)end;local door=part(puzzles,"ColorDoor",Vector3.new(26,12,2),CFrame.new(0,10,105),Color3.fromRGB(110,75,45));door:SetAttribute("PuzzleId","ColorDoor");local box=part(puzzles,"PushBox",Vector3.new(4,4,4),CFrame.new(-7,7,145),Color3.fromRGB(125,80,45));box.Anchored=false;local plate=part(puzzles,"PressurePlate",Vector3.new(6,.5,6),CFrame.new(7,5,145),Color3.fromRGB(80,220,100));plate:SetAttribute("PuzzleId","PushBox")end
	return map
end
return Service
