--!strict
local ReplicatedStorage=game:GetService("ReplicatedStorage");local VoteConfig=require(ReplicatedStorage.Modules.MapVoteConfig);local Maps=require(script.Parent.MapService);local Events=require(script.Parent.GameplayEventService);local remotes=require(script.Parent.RemoteService).Ensure();local Service={};local active:any=nil;local lastRanked:string?=nil;local forcedMap:string?=nil
function Service.SetForcedMap(mapId:string?)forcedMap=mapId end
function Service.Submit(p:Player,mapId:string):boolean if not active or os.clock()>active.endsAt or not table.find(active.players,p)or not active.candidateIds[mapId]then return false end;local first=active.votes[p]==nil;active.votes[p]=mapId;if first then Events.Event:Fire(p,"MapVote",1)end;local counts={};for _,id in active.votes do counts[id]=(counts[id]or 0)+1 end;for _,x in active.players do remotes.MapVoteUpdated:FireClient(x,{counts=counts,selected=active.votes[x]})end;return true end
function Service.Select(modeId:string,players:{Player}):string?
	local eligible=Maps.GetEligibleMaps(modeId);if #eligible==0 then return nil end
	if forcedMap then local selected=forcedMap;forcedMap=nil;for _,definition in eligible do if definition.Id==selected then return selected end end;warn("[StudioHelper] forced map is not eligible: "..selected)end
	if modeId=="RankedRace"then local choices={};for _,d in eligible do if d.Id~=lastRanked then table.insert(choices,d)end end;if #choices==0 then choices=eligible end;local selected=choices[math.random(1,#choices)].Id;lastRanked=selected;return selected end
	for i=#eligible,2,-1 do local j=math.random(i);eligible[i],eligible[j]=eligible[j],eligible[i]end;local candidates={};local ids={};for i=1,math.min(VoteConfig.MaximumCandidates,#eligible)do table.insert(candidates,eligible[i]);ids[eligible[i].Id]=true end;active={players=players,candidateIds=ids,votes={},endsAt=os.clock()+VoteConfig.Duration};for _,p in players do remotes.MapVoteStarted:FireClient(p,{candidates=candidates,duration=VoteConfig.Duration})end;task.wait(VoteConfig.Duration);local counts={};for _,id in active.votes do counts[id]=(counts[id]or 0)+1 end;local best=-1;local tied={};for _,d in candidates do local n=counts[d.Id]or 0;if n>best then best=n;tied={d.Id}elseif n==best then table.insert(tied,d.Id)end end;local selected=tied[math.random(1,#tied)];active=nil;for _,p in players do remotes.MapSelected:FireClient(p,{mapId=selected,definition=Maps.GetMapDefinition(selected)})end;return selected
end
return Service
