--!strict
local Players=game:GetService("Players");local ReplicatedStorage=game:GetService("ReplicatedStorage");local Config=require(ReplicatedStorage.Modules.DataConfig);local Template=require(ReplicatedStorage.Modules.PlayerDataTemplate);local Wrapper=require(script.Parent.DataStoreServiceWrapper)
export type Profile={[string]:any};type Record={Data:Profile,Dirty:boolean,Revision:number,Saving:boolean,Loaded:boolean,MemoryMode:boolean,LoadedAt:number}
local records:{[Player]:Record}={};local loading:{[Player]:boolean}={};local Service={Changed=Instance.new("BindableEvent")}
local function clone(value:any):any if type(value)~="table" then return value end;local out={};for k,v in value do out[k]=clone(v) end;return out end
local function reconcile(target:any,template:any):any if type(target)~=type(template) then return clone(template) end;if type(template)=="table" then for k,v in template do target[k]=reconcile(target[k],v) end end;return target end
local function pathParts(path:string):{string} return string.split(path,".") end
local function locate(data:any,path:string):(any,string) local parts=pathParts(path);local node=data;for i=1,#parts-1 do local key=parts[i];if type(node[key])~="table" then node[key]={} end;node=node[key] end;return node,parts[#parts] end
function Service.ReconcileProfile(profile:Profile):Profile profile=reconcile(profile,Template);profile.DataVersion=Template.DataVersion;return profile end
function Service.LoadProfile(player:Player):(boolean,string?)
	if records[player] then return true,nil end;if loading[player] then local deadline=os.clock()+Config.ProfileLoadTimeout;while loading[player] and os.clock()<deadline do task.wait(.1) end;return records[player]~=nil,"concurrent load timeout" end;loading[player]=true
	local data,memoryMode,err=Wrapper.Load("Player_"..player.UserId,Template);loading[player]=nil;if not data then return false,err end;data=Service.ReconcileProfile(data);data.General.JoinCount+=1;data.General.LastJoinTimestamp=os.time();records[player]={Data=data,Dirty=true,Revision=1,Saving=false,Loaded=true,MemoryMode=memoryMode,LoadedAt=os.clock()};if memoryMode then print(string.format("[Data] created memory profile for %s",player.Name))else print(string.format("[Data] loaded profile for %s",player.Name))end;print(string.format("[Data] reconciled profile version %d",data.DataVersion));Service.Changed:Fire(player,Service.GetPublicProfileSnapshot(player));return true,err
end
function Service.GetProfile(player:Player):Profile? local r=records[player];return r and r.Data end
function Service.Get(player:Player):Profile local deadline=os.clock()+Config.ProfileLoadTimeout;while not records[player] and player.Parent==Players and os.clock()<deadline do task.wait(.1) end;local r=records[player];if not r then error("Profile not loaded for "..player.Name) end;return r.Data end
function Service.IsProfileLoaded(player:Player):boolean return records[player]~=nil end
function Service.IsMemoryMode(player:Player):boolean local r=records[player];return r~=nil and r.MemoryMode end
function Service.MarkDirty(player:Player) local r=records[player];if r then r.Dirty=true;r.Revision+=1 end end
function Service.UpdateValue(player:Player,path:string,value:any):boolean local r=records[player];if not r then return false end;local node,key=locate(r.Data,path);node[key]=value;Service.MarkDirty(player);Service.Changed:Fire(player,Service.GetPublicProfileSnapshot(player));return true end
function Service.IncrementValue(player:Player,path:string,amount:number):number? local r=records[player];if not r then return nil end;local node,key=locate(r.Data,path);if type(node[key])~="number" then return nil end;node[key]+=amount;Service.MarkDirty(player);Service.Changed:Fire(player,Service.GetPublicProfileSnapshot(player));return node[key] end
function Service.AddOwnedCosmetic(player:Player,id:string):boolean local p=Service.GetProfile(player);if not p or p.Inventory.OwnedCosmetics[id] then return false end;p.Inventory.OwnedCosmetics[id]=true;Service.MarkDirty(player);return true end
function Service.PurchaseCosmetic(player:Player,id:string,price:number):boolean local p=Service.GetProfile(player);if not p or p.Inventory.OwnedCosmetics[id] or p.Economy.Coins<price then return false end;p.Economy.Coins-=price;p.Economy.TotalCoinsSpent+=price;p.Inventory.OwnedCosmetics[id]=true;Service.MarkDirty(player);Service.Changed:Fire(player,Service.GetPublicProfileSnapshot(player));return true end
function Service.OwnsCosmetic(player:Player,id:string):boolean local p=Service.GetProfile(player);return p~=nil and p.Inventory.OwnedCosmetics[id]==true end
function Service.EquipCosmetic(player:Player,slot:string,id:string):boolean local p=Service.GetProfile(player);if not p or not Service.OwnsCosmetic(player,id) or p.Inventory.EquippedCosmetics[slot]==nil then return false end;p.Inventory.EquippedCosmetics[slot]=id;Service.MarkDirty(player);Service.Changed:Fire(player,Service.GetPublicProfileSnapshot(player));return true end
function Service.UnequipCosmetic(player:Player,slot:string):boolean local p=Service.GetProfile(player);if not p or p.Inventory.EquippedCosmetics[slot]==nil then return false end;p.Inventory.EquippedCosmetics[slot]="";Service.MarkDirty(player);Service.Changed:Fire(player,Service.GetPublicProfileSnapshot(player));return true end
function Service.AddConsumable(player:Player,id:string,amount:number):boolean local p=Service.GetProfile(player);if not p or type(p.Inventory.Consumables[id])~="number" then return false end;p.Inventory.Consumables[id]+=amount;Service.MarkDirty(player);return true end
function Service.ConsumeConsumable(player:Player,id:string,amount:number):boolean local p=Service.GetProfile(player);if not p or type(p.Inventory.Consumables[id])~="number" or p.Inventory.Consumables[id]<amount then return false end;p.Inventory.Consumables[id]-=amount;Service.MarkDirty(player);return true end
function Service.GetPublicProfileSnapshot(player:Player):any local p=Service.GetProfile(player);if not p then return nil end;local owned={};for id,value in p.Inventory.OwnedCosmetics do if value then table.insert(owned,id) end end;return {coins=p.Economy.Coins,rankPoints=p.RankedRace.RankPoints,rankId=p.RankedRace.RankId,division=p.RankedRace.Division,wins=p.General.Wins,bestRaceTime=p.CasualRace.BestTimeMilliseconds,bestTowerTime=p.Tower.BestTowerTimes.Tower01 or 0,ownedCosmeticIds=owned,equippedCosmetics=clone(p.Inventory.EquippedCosmetics),consumableCounts=clone(p.Inventory.Consumables),gamePasses=clone(p.Monetization.OwnedGamePasses),daily={lastClaim=p.DailyRewards.LastClaimTimestamp,streak=p.DailyRewards.CurrentStreak},memoryMode=records[player].MemoryMode} end
function Service.SaveProfile(player:Player,reason:string,release:boolean?):boolean local r=records[player];if not r or r.Saving then return false end;if not r.Dirty and not release then return true end;r.Saving=true;local revision=r.Revision;r.Data.General.TotalPlaySeconds+=math.floor(os.clock()-r.LoadedAt);r.LoadedAt=os.clock();r.Data.General.LastSaveTimestamp=os.time();local success=false;for attempt=1,Config.SaveRetryCount do local ok,err=Wrapper.Save("Player_"..player.UserId,r.Data,release==true,r.MemoryMode);if ok then success=true;break end;warn(string.format("[Data] failed to save %s, retry %d/%d: %s",player.Name,attempt,Config.SaveRetryCount,tostring(err)));task.wait(Config.RetryBaseDelay*attempt) end;r.Saving=false;if success and r.Revision==revision then r.Dirty=false end;if success then print(string.format("[Data] saved %s on %s",player.Name,reason)) end;return success end
function Service.ReleaseProfile(player:Player) local r=records[player];if r then local deadline=os.clock()+10;while r.Saving and os.clock()<deadline do task.wait(.1) end;Service.SaveProfile(player,"PlayerRemoving",true);records[player]=nil;print(string.format("[Data] released session lock for %s",player.Name)) end end
return Service
