--!strict
local Players=game:GetService("Players");local TweenService=game:GetService("TweenService");local RunService=game:GetService("RunService");local Config=require(game:GetService("ReplicatedStorage").Modules.PuzzleConfig);local Registry=require(script.Parent.ConnectionRegistry);local Race=require(script.Parent.RaceService);local remotes=require(script.Parent.RemoteService).Ensure();local Service={};local states:{[string]:any}={}
local function player(hit:BasePart):Player?local n:Instance?=hit;while n and n~=workspace do if n:IsA("Model")and n:FindFirstChildOfClass("Humanoid")then return Players:GetPlayerFromCharacter(n)end;n=n.Parent end;return nil end
local function open(door:BasePart?)if door then door.CanCollide=false;door.Transparency=.72 end end
function Service.Bind(matchId:string,map:Folder)
	local puzzles=map:FindFirstChild("Puzzles");if not puzzles then return end;local owner="Puzzle:"..matchId;local state={players={},pushComplete=false,levers={},tweens={}};states[matchId]=state
	local colorDoor=puzzles:FindFirstChild("ColorDoor")::BasePart?
	for _,button in puzzles:GetChildren()do if button:IsA("BasePart")and button:GetAttribute("PuzzleId")=="ColorDoor"and button:GetAttribute("Step")then Registry.Register(button.Touched:Connect(function(hit)local p=player(hit);if not p then return end;local s=state.players[p]or{step=1,started=os.clock(),completed=false};state.players[p]=s;if s.completed then return end;if button:GetAttribute("Step")==Config.WorkshopColorSequence[s.step]then s.step+=1;if s.step>#Config.WorkshopColorSequence then s.completed=true;open(colorDoor);remotes.PuzzleMessage:FireClient(p,"顏色順序正確！")end else s.step=1;remotes.PuzzleMessage:FireClient(p,"順序錯誤，重新開始")end end),owner,"Touched")end end
	local box=puzzles:FindFirstChild("PushBox")::BasePart?;local plate=puzzles:FindFirstChild("PressurePlate")::BasePart?;local pushDoor=puzzles:FindFirstChild("PushDoor")::BasePart?;if box and plate then local origin=box.CFrame;Registry.Register(plate.Touched:Connect(function(hit)if hit==box then state.pushComplete=true;open(pushDoor)end end),owner,"Touched");local reset=puzzles:FindFirstChild("ResetPushBox");local prompt=reset and reset:FindFirstChildOfClass("ProximityPrompt");if prompt then Registry.Register(prompt.Triggered:Connect(function(p)local data=Race.Get(p);if state.pushComplete or Race.State~="Racing"or not data or not data.IsRacing then return end;box.CFrame=origin;box.AssemblyLinearVelocity=Vector3.zero;box.AssemblyAngularVelocity=Vector3.zero;remotes.PuzzleMessage:FireClient(p,"木箱已重置")end),owner,"Prompt")end;Registry.Register(RunService.Heartbeat:Connect(function()if not box.Parent then return end;if (box.Position-origin.Position).Magnitude>35 or box.Position.Y<0 then box.CFrame=origin;box.AssemblyLinearVelocity=Vector3.zero;box.AssemblyAngularVelocity=Vector3.zero end end),owner,"Heartbeat")end
	local moving=puzzles:FindFirstChild("MovingWalls");if moving then for _,wall in moving:GetChildren()do if wall:IsA("BasePart")then local offset=wall:GetAttribute("MoveOffset")or 5;local tween=TweenService:Create(wall,TweenInfo.new(3,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,-1,true),{Position=wall.Position+Vector3.new(offset,0,0)});table.insert(state.tweens,tween);tween:Play()end end end
	local finalDoor=puzzles:FindFirstChild("FinalDoor")::BasePart?;for _,lever in puzzles:GetChildren()do if lever:IsA("BasePart")and lever:GetAttribute("PuzzleId")=="FinalLevers"then local prompt=lever:FindFirstChildOfClass("ProximityPrompt");if prompt then Registry.Register(prompt.Triggered:Connect(function(p)local index=lever:GetAttribute("LeverIndex");if not state.levers[index]then state.levers[index]=true;local count=0;for _ in state.levers do count+=1 end;remotes.PuzzleMessage:FireClient(p,string.format("終點拉桿 %d/2",count));if count>=2 then open(finalDoor)end end end),owner,"Prompt")end end end
	task.delay(Config.HintTime,function()if states[matchId]then for p,s in state.players do if not s.completed then remotes.PuzzleMessage:FireClient(p,"提示：紅、藍、綠")end end end end);task.delay(Config.AutoCompleteTime,function()if states[matchId]then open(colorDoor);open(pushDoor);open(finalDoor)end end)
end
function Service.Clear(matchId:string)local state=states[matchId];if state then for _,tween in state.tweens do tween:Cancel()end end;local before=(Registry.GetCountsByOwner()["Puzzle:"..matchId]or 0);Registry.DisconnectOwner("Puzzle:"..matchId);states[matchId]=nil;print(string.format("[Diagnostics] Match %s connections before cleanup: %d",matchId,before));print(string.format("[Diagnostics] Match %s connections after cleanup: 0",matchId))end
return Service
