--!strict
local RunService=game:GetService("RunService")
local Config=require(game:GetService("ReplicatedStorage").Modules.DevelopmentConfig)
local Service={}
local enabled=RunService:IsStudio() and Config.EnableStudioTestHelpers
local function allowed():boolean if not enabled then warn("[StudioHelper] unavailable outside Studio");return false end;return true end
function Service.JoinCasual(player:Player):boolean if not allowed()then return false end;return require(script.Parent.QueueService).Join(player,"CasualRace")end
function Service.StartSoloTower(player:Player,towerId:string):boolean if not allowed()then return false end;return require(script.Parent.TowerService).Start(player,towerId)end
function Service.ForceNextMap(mapId:string)if not allowed()then return end;require(script.Parent.MapVoteService).SetForcedMap(mapId);print("[StudioHelper] next race map: "..mapId)end
function Service.ForceCasualMap(mapId:string)Service.ForceNextMap(mapId)end
function Service.TeleportToCheckpoint(player:Player,index:number):boolean if not allowed()then return false end;local mode=require(script.Parent.ModeService).Get(player);local map=mode.CurrentMatchId and require(script.Parent.MapService).GetLoadedMap(mode.CurrentMatchId);local cp=map and map:FindFirstChild("Checkpoints") and map.Checkpoints:FindFirstChild(string.format("Checkpoint%02d",index));local root=player.Character and player.Character:FindFirstChild("HumanoidRootPart");if cp and cp:IsA("BasePart")and root and root:IsA("BasePart")then root.CFrame=cp.CFrame+Vector3.new(0,4,0);return true end;return false end
function Service.TeleportToTowerFloor(player:Player,towerIdOrIndex:string|number,index:number?):boolean if not allowed()then return false end;local session=require(script.Parent.TowerService).Get(player);local towerId=if type(towerIdOrIndex)=="string"then towerIdOrIndex else session and session.mapId;local floorIndex=if type(towerIdOrIndex)=="number"then towerIdOrIndex else index;local world=workspace:FindFirstChild("PartyObbyWorld");local map=towerId and world and world:FindFirstChild("TowerMaps") and world.TowerMaps:FindFirstChild(towerId);local floors=map and map:FindFirstChild("Floors");local floor=floors and floorIndex and floors:FindFirstChild(string.format("Floor%02d",floorIndex));local root=player.Character and player.Character:FindFirstChild("HumanoidRootPart");if floor and floor:IsA("BasePart")and root and root:IsA("BasePart")then root.CFrame=floor.CFrame+Vector3.new(0,4,0);return true end;return false end
function Service.ValidateTowerPath(towerId:string):boolean if not allowed()then return false end;local world=workspace:FindFirstChild("PartyObbyWorld");local towerMaps=world and world:FindFirstChild("TowerMaps");local tower=towerMaps and towerMaps:FindFirstChild(towerId);if not tower then warn("[StudioHelper] tower missing: "..towerId);return false end;local validator=require(script.Parent.TowerPathValidator);local results=validator.Validate(tower);validator.Print(results);return not validator.HasFailures(results)end
function Service.ShowJumpNodes(towerId:string,visible:boolean):boolean if not allowed()then return false end;local world=workspace:FindFirstChild("PartyObbyWorld");local towerMaps=world and world:FindFirstChild("TowerMaps");local tower=towerMaps and towerMaps:FindFirstChild(towerId);if not tower then return false end;for _,item in tower:GetDescendants()do if item:IsA("BasePart")and item:GetAttribute("JumpOrder")then item.Transparency=if visible then .35 else 1 end end;return true end
function Service.ShowTowerClearanceBoxes(towerId:string,visible:boolean):boolean if not allowed()then return false end;local world=workspace:FindFirstChild("PartyObbyWorld");local maps=world and world:FindFirstChild("TowerMaps");local tower=maps and maps:FindFirstChild(towerId);if not tower then return false end;return require(script.Parent.TowerPathValidator).ShowClearanceBoxes(tower,visible)end
function Service.ShowState(player:Player)local mode=require(script.Parent.ModeService).Get(player);local Registry=require(script.Parent.ConnectionRegistry);print(string.format("[StudioHelper] %s mode=%s match=%s map=%s connections=%d",player.Name,tostring(mode.CurrentMode),tostring(mode.CurrentMatchId),tostring(mode.CurrentMapId),Registry.GetActiveCount()))end
function Service.ResetTowerPlayer(player:Player):boolean if not allowed()then return false end;return require(script.Parent.TowerService).Fall(player,"StudioHelper")end
function Service.EndCurrentMode(player:Player)if allowed()then require(script.Parent.LobbyService).Return(player)end end
function Service.ReturnPlayerToLobby(player:Player)Service.ReturnToLobby(player)end
function Service.PrintUIState(player:Player)if allowed()then local payload=require(script.Parent.ModeService).Payload(player);print(string.format("[StudioHelper] UI state for %s: %s",player.Name,tostring(payload.uiState)))end end
function Service.PrintConnectionCounts()if allowed()then local registry=require(script.Parent.ConnectionRegistry);print("[StudioHelper] connections: "..registry.GetActiveCount());for owner,count in registry.GetCountsByOwner()do print(string.format("[StudioHelper] %s = %d",owner,count))end end end
function Service.ReturnToLobby(player:Player)if allowed()then require(script.Parent.LobbyService).Return(player)end end
return Service
