--!strict
local Mode=require(script.Parent.ModeService);local Profiles=require(script.Parent.PlayerProfileService);local Items=require(script.Parent.ItemService);local Movement=require(script.Parent.MovementModifierService);local Spawn=require(script.Parent.TowerSpawnService);local Config=require(game:GetService("ReplicatedStorage").Modules.TowerConfig);local remotes=require(script.Parent.RemoteService).Ensure();local Tower={};local sessions:{[Player]:any}={}
local function map(id:string):Folder?local world=workspace:FindFirstChild("PartyObbyWorld");local maps=world and world:FindFirstChild("TowerMaps");local value=maps and maps:FindFirstChild(id);return if value and value:IsA("Folder")then value else nil end
function Tower.Start(p:Player,id:string?):boolean
	id=id or"Tower01";local definition=Config[id];local tower=definition and map(id);if not definition or not tower or not Profiles.IsProfileLoaded(p)then return false end;local start=tower:FindFirstChild("TowerStart");if not start or not start:IsA("BasePart")then return false end;local mode=Mode.Get(p);if mode.IsQueued or mode.IsInMatch or mode.IsInTower then return false end;Items.ClearPlayer(p);mode.CurrentMode=id=="Tower01"and"SoloTower"or"SoloTower02";mode.IsInLobby=false;mode.IsInTower=true;mode.CurrentMapId=id;mode.CurrentMatchId=id.."-"..p.UserId.."-"..math.floor(os.clock()*1000);local profile=Profiles.GetProfile(p);local bestMs=profile and(profile.Tower.BestTowerTimes[id]or 0)or 0;sessions[p]={floor=0,started=0,lastCFrame=start.CFrame,lastSupport=start,active=false,runId=mode.CurrentMatchId,mapId=id,floorCount=definition.FloorCount,falls=0};if not Spawn.Teleport(p,tower,start)then warn("[Tower] unsafe spawn detected for "..id);sessions[p]=nil;require(script.Parent.LobbyService).Return(p);return false end;Movement.AddModifier(p,"TowerStartLock",0);remotes.ModeStateChanged:FireClient(p,{mode=mode.CurrentMode,inTower=true,towerId=id});task.spawn(function()for n=3,1,-1 do remotes.TowerProgressUpdated:FireClient(p,{floor=0,total=definition.FloorCount,best=bestMs/1000,countdown=n,towerId=id});task.wait(1)end;local session=sessions[p];if session then session.started=os.clock();session.active=true;Movement.RemoveModifier(p,"TowerStartLock");remotes.TowerProgressUpdated:FireClient(p,{floor=0,total=definition.FloorCount,best=bestMs/1000,countdown="GO",towerId=id});print(string.format("[Tower] %s started %s",p.Name,id))end end);return true
end
function Tower.Respawn(p:Player):boolean local session=sessions[p];local tower=session and map(session.mapId);local support=session and session.lastSupport;if not tower or not support or not support:IsA("BasePart")then return false end;if Spawn.Teleport(p,tower,support)then return true end;warn("[Tower] unsafe spawn detected for "..session.mapId);Tower.Leave(p);require(script.Parent.LobbyService).Return(p);return false end
function Tower.Leave(p:Player)local s=sessions[p];if s then require(script.Parent.ConnectionRegistry).DisconnectOwner("TowerRun:"..s.runId)end;sessions[p]=nil end
function Tower.Session(p:Player):any return sessions[p]end
function Tower.Count():number local n=0;for _ in sessions do n+=1 end;return n end
return Tower
