--!strict
local RunService=game:GetService("RunService");local ReplicatedStorage=game:GetService("ReplicatedStorage");local Mode=require(script.Parent.ModeService);local Profiles=require(script.Parent.PlayerProfileService);local Items=require(script.Parent.ItemService);local Movement=require(script.Parent.MovementModifierService);local Spawn=require(script.Parent.TowerSpawnService);local Registry=require(script.Parent.ConnectionRegistry);local Config=require(ReplicatedStorage.Modules.TowerConfig);local remotes=require(script.Parent.RemoteService).Ensure()
local Tower={};local sessions:{[Player]:any}={}
local function map(id:string):Folder?local world=workspace:FindFirstChild("PartyObbyWorld");local maps=world and world:FindFirstChild("TowerMaps");local value=maps and maps:FindFirstChild(id);return if value and value:IsA("Folder")then value else nil end
local function modeState(p:Player,session:any,uiState:string)remotes.ModeStateChanged:FireClient(p,{mode=Mode.Get(p).CurrentMode,inTower=true,towerId=session.towerId,runId=session.runId,uiState=uiState})end
function Tower.Start(p:Player,id:string?):boolean
	id=id or"Tower01";if sessions[p]then return false end;local definition=Config[id];local tower=definition and map(id);if not definition or not tower or not Profiles.IsProfileLoaded(p)then return false end;local start=tower:FindFirstChild("TowerStart");if not start or not start:IsA("BasePart")then return false end
	local mode=Mode.Get(p);if mode.IsQueued or mode.IsInMatch or mode.IsInTower then return false end;Items.ClearPlayer(p);mode.CurrentMode=id=="Tower01"and"SoloTower"or"SoloTower02";mode.IsInLobby=false;mode.IsInTower=true;mode.CurrentMapId=id;mode.CurrentMatchId=id.."-"..p.UserId.."-"..math.floor(workspace:GetServerTimeNow()*1000)
	local profile=Profiles.GetProfile(p);local bestMs=profile and(profile.Tower.BestTowerTimes[id]or 0)or 0;local session={runId=mode.CurrentMatchId,towerId=id,mapId=id,player=p,state="Preparing",currentFloor=0,floor=0,floorCount=definition.FloorCount,startTime=0,started=0,finishTime=0,falls=0,puzzleState={},lastCheckpointCFrame=start.CFrame,lastCFrame=start.CFrame,lastSupport=start,isFinished=false,rewardGranted=false,active=false,lastFallAt=0};sessions[p]=session
	if not Spawn.Teleport(p,tower,start)then warn("[Tower] unsafe spawn detected for "..id);sessions[p]=nil;require(script.Parent.LobbyService).Return(p);return false end;Movement.AddModifier(p,"TowerStartLock",0);modeState(p,session,"TowerPreparing")
	Registry.Register(RunService.Heartbeat:Connect(function()local current=sessions[p];if not current or current.runId~=session.runId then return end;local root=p.Character and p.Character:FindFirstChild("HumanoidRootPart");local kill=tower:FindFirstChild("KillFloor");local killHeight=if kill and kill:IsA("BasePart")then kill.Position.Y+2 else start.Position.Y-25;if current.state=="Running"and root and root:IsA("BasePart")and root.Position.Y<killHeight then Tower.Fall(p,"KillHeight")end end),"TowerRun:"..session.runId,"Heartbeat")
	task.spawn(function()session.state="Countdown";modeState(p,session,"TowerCountdown");for n=3,1,-1 do if sessions[p]~=session then return end;remotes.TowerProgressUpdated:FireClient(p,{state=session.state,floor=0,total=definition.FloorCount,best=bestMs/1000,countdown=n,towerId=id,runId=session.runId});task.wait(1)end;if sessions[p]~=session then return end;session.startTime=workspace:GetServerTimeNow();session.started=session.startTime;session.state="Running";session.active=true;Movement.RemoveModifier(p,"TowerStartLock");modeState(p,session,"TowerRunning");remotes.TowerProgressUpdated:FireClient(p,{state=session.state,floor=0,total=definition.FloorCount,best=bestMs/1000,countdown="GO",serverStartTime=session.startTime,towerId=id,runId=session.runId});print(string.format("[Tower] %s started %s run %s",p.Name,id,session.runId))end);return true
end
function Tower.Fall(p:Player,reason:string?):boolean local session=sessions[p];if not session or session.state~="Running"then return false end;local now=os.clock();if now-session.lastFallAt<1 then return false end;session.lastFallAt=now;session.falls+=1;Profiles.IncrementValue(p,"Tower.TotalFalls",1);print(string.format("[Tower] %s fall %d (%s)",p.Name,session.falls,reason or"unknown"));return Tower.Respawn(p)end
function Tower.Respawn(p:Player):boolean local session=sessions[p];local tower=session and map(session.towerId);local support=session and session.lastSupport;if not tower or not support or not support:IsA("BasePart")then return false end;Movement.ClearTemporaryModifiers(p);if Spawn.Teleport(p,tower,support)then return true end;warn("[Tower] unsafe respawn detected for "..session.towerId);Tower.Leave(p);require(script.Parent.LobbyService).Return(p);return false end
function Tower.Leave(p:Player)local session=sessions[p];if not session then return end;session.state="Exited";session.active=false;Movement.RemoveModifier(p,"TowerStartLock");Registry.DisconnectOwner("TowerRun:"..session.runId);sessions[p]=nil end
function Tower.Session(p:Player):any return sessions[p]end
function Tower.Get(p:Player):any return sessions[p]end
function Tower.Count():number local n=0;for _ in sessions do n+=1 end;return n end
return Tower
