--!strict
local Players=game:GetService("Players");local ReplicatedStorage=game:GetService("ReplicatedStorage");local player=Players.LocalPlayer;print("[LobbyUI] client started");local Controller=require(script.Parent.UIStateController);print("[LobbyUI] UI state controller ready")
local old=player.PlayerGui:FindFirstChild("LobbyGui");if old then old:Destroy()end
local gui=Instance.new("ScreenGui");gui.Name="LobbyGui";gui.ResetOnSpawn=false;gui.IgnoreGuiInset=false;gui.Parent=player.PlayerGui
local container=Instance.new("Frame");container.Name="LobbyMenuContainer";container.AnchorPoint=Vector2.new(0,.5);container.Position=UDim2.fromScale(.02,.55);container.Size=UDim2.fromScale(.14,.58);container.BackgroundColor3=Color3.fromRGB(24,31,46);container.BackgroundTransparency=.18;container.Parent=gui;Instance.new("UICorner",container).CornerRadius=UDim.new(.06,0)
local constraint=Instance.new("UISizeConstraint");constraint.MinSize=Vector2.new(150,260);constraint.MaxSize=Vector2.new(210,500);constraint.Parent=container
local padding=Instance.new("UIPadding");padding.PaddingTop=UDim.new(.025,0);padding.PaddingBottom=UDim.new(.025,0);padding.PaddingLeft=UDim.new(.05,0);padding.PaddingRight=UDim.new(.05,0);padding.Parent=container
local layout=Instance.new("UIListLayout");layout.FillDirection=Enum.FillDirection.Vertical;layout.HorizontalAlignment=Enum.HorizontalAlignment.Center;layout.VerticalAlignment=Enum.VerticalAlignment.Center;layout.Padding=UDim.new(.012,0);layout.SortOrder=Enum.SortOrder.LayoutOrder;layout.Parent=container
local function button(text:string,order:number,action:()->())local b=Instance.new("TextButton");b.Name=text.."Button";b.LayoutOrder=order;b.Size=UDim2.new(1,0,.13,0);b.Text=text;b.TextScaled=true;b.TextColor3=Color3.new(1,1,1);b.BackgroundColor3=Color3.fromRGB(55,105,155);b.Selectable=true;b.Parent=container;Instance.new("UICorner",b).CornerRadius=UDim.new(.16,0);b.Activated:Connect(action)end
button("模式",1,function()Controller.OpenExclusive("ModeSelectionGui")end);button("商店",2,function()Controller.OpenExclusive("ShopGui")end);button("背包",3,function()Controller.OpenExclusive("InventoryGui")end);button("牌位",4,function()Controller.OpenExclusive("RankGui")end);button("任務",5,function()Controller.OpenExclusive("QuestGui")end);button("設定",6,function()Controller.OpenExclusive("SettingsGui")end)
button("新手教學",7,function()Controller.OpenExclusive("TutorialGui");local remote=ReplicatedStorage.Remotes:FindFirstChild("RestartTutorial");if remote and remote:IsA("RemoteEvent")then remote:FireServer()end end)
Controller.Apply()
