--!strict
local Players=game:GetService("Players");local ReplicatedStorage=game:GetService("ReplicatedStorage");local player=Players.LocalPlayer;local modes=require(ReplicatedStorage.Modules.ModeConfig);local folder=ReplicatedStorage:WaitForChild("Remotes",10);if not folder then return end;local selectRemote=folder:WaitForChild("SelectMode")::RemoteEvent;local open=folder:WaitForChild("OpenMenu")::RemoteEvent
local gui=Instance.new("ScreenGui");gui.Name="ModeSelectionGui";gui.ResetOnSpawn=false;gui.Enabled=false;gui.Parent=player.PlayerGui;local frame=Instance.new("Frame");frame.Position=UDim2.fromScale(.2,.15);frame.Size=UDim2.fromScale(.6,.68);frame.BackgroundColor3=Color3.fromRGB(25,32,48);frame.BackgroundTransparency=.08;frame.Parent=gui;Instance.new("UICorner",frame).CornerRadius=UDim.new(.04,0)
local title=Instance.new("TextLabel");title.Size=UDim2.fromScale(1,.12);title.BackgroundTransparency=1;title.Text="爆笑村莊廣場・選擇模式";title.TextScaled=true;title.TextColor3=Color3.new(1,1,1);title.Font=Enum.Font.GothamBold;title.Parent=frame
local pending:string?=nil;local confirm=Instance.new("TextLabel");confirm.Position=UDim2.fromScale(.08,.72);confirm.Size=UDim2.fromScale(.84,.1);confirm.BackgroundTransparency=1;confirm.Text="";confirm.TextScaled=true;confirm.TextColor3=Color3.fromRGB(255,225,90);confirm.Parent=frame
local join=Instance.new("TextButton");join.Position=UDim2.fromScale(.2,.84);join.Size=UDim2.fromScale(.25,.1);join.Text="加入";join.TextScaled=true;join.BackgroundColor3=Color3.fromRGB(70,195,110);join.Parent=frame
local cancel=Instance.new("TextButton");cancel.Position=UDim2.fromScale(.55,.84);cancel.Size=UDim2.fromScale(.25,.1);cancel.Text="取消";cancel.TextScaled=true;cancel.BackgroundColor3=Color3.fromRGB(190,80,80);cancel.Parent=frame
local ids={"CasualRace","RankedRace","SoloTower","SoloTower02"};for i,id in ids do local m=modes[id];local col=(i-1)%2;local row=math.floor((i-1)/2);local b=Instance.new("TextButton");b.Position=UDim2.fromScale(.07+col*.47,.15+row*.27);b.Size=UDim2.fromScale(.4,.23);b.Text=string.format("%s\n%s\n%d～%d 人・%s",m.DisplayName,m.Description,m.MinimumPlayers,m.MaximumPlayers,m.IsRanked and "影響牌位" or "不影響牌位");b.TextWrapped=true;b.TextScaled=true;b.BackgroundColor3=m.IsRanked and Color3.fromRGB(180,130,45) or Color3.fromRGB(55,115,165);b.TextColor3=Color3.new(1,1,1);b.Parent=frame;b.Selectable=true;b.Activated:Connect(function()pending=id;confirm.Text="是否加入「"..m.DisplayName.."」？"end)end
join.Activated:Connect(function() if pending then selectRemote:FireServer(pending);gui.Enabled=false;pending=nil end end);cancel.Activated:Connect(function()pending=nil;confirm.Text="";gui.Enabled=false end)
open.OnClientEvent:Connect(function(data)gui.Enabled=true;if data.confirmMode and modes[data.confirmMode] then pending=data.confirmMode;confirm.Text="是否加入「"..modes[pending].DisplayName.."」？" end end)
