--!strict
local Players=game:GetService("Players");local ReplicatedStorage=game:GetService("ReplicatedStorage");local player=Players.LocalPlayer;local remotes=ReplicatedStorage:WaitForChild("Remotes",10);if not remotes then return end;local updated=remotes:WaitForChild("ProfileUpdated")::RemoteEvent;local request=remotes:WaitForChild("RequestProfile")::RemoteEvent;local claim=remotes:WaitForChild("ClaimDailyReward")::RemoteEvent
local old=player.PlayerGui:FindFirstChild("ProfileGui");if old then old:Destroy()end;local gui=Instance.new("ScreenGui");gui.Name="ProfileGui";gui.ResetOnSpawn=false;gui.IgnoreGuiInset=false;gui.Parent=player.PlayerGui
local stats=Instance.new("Frame");stats.Position=UDim2.fromScale(.025,.025);stats.Size=UDim2.fromScale(.18,.075);stats.BackgroundColor3=Color3.fromRGB(38,45,65);stats.BackgroundTransparency=.12;stats.Parent=gui;local statsConstraint=Instance.new("UISizeConstraint");statsConstraint.MinSize=Vector2.new(180,42);statsConstraint.MaxSize=Vector2.new(290,58);statsConstraint.Parent=stats;local padding=Instance.new("UIPadding");padding.PaddingLeft=UDim.new(0,8);padding.PaddingRight=UDim.new(0,8);padding.Parent=stats;local list=Instance.new("UIListLayout");list.FillDirection=Enum.FillDirection.Horizontal;list.VerticalAlignment=Enum.VerticalAlignment.Center;list.Padding=UDim.new(0,12);list.Parent=stats
local function text(parent:Instance,name:string):TextLabel local label=Instance.new("TextLabel");label.Name=name;label.Size=UDim2.new(.5,-6,1,0);label.BackgroundTransparency=1;label.TextColor3=Color3.new(1,1,1);label.TextScaled=true;label.Parent=parent;return label end
local coins=text(stats,"Coins");local wins=text(stats,"Wins")
local rank=Instance.new("TextLabel");rank.AnchorPoint=Vector2.new(.5,0);rank.Position=UDim2.fromScale(.5,.025);rank.Size=UDim2.fromScale(.25,.065);rank.BackgroundColor3=Color3.fromRGB(90,65,35);rank.BackgroundTransparency=.12;rank.TextColor3=Color3.new(1,1,1);rank.TextScaled=true;rank.Parent=gui;local rankConstraint=Instance.new("UISizeConstraint");rankConstraint.MinSize=Vector2.new(220,38);rankConstraint.MaxSize=Vector2.new(380,52);rankConstraint.Parent=rank
local test=Instance.new("TextLabel");test.AnchorPoint=Vector2.new(1,0);test.Position=UDim2.fromScale(.975,.025);test.Size=UDim2.fromScale(.15,.065);test.BackgroundColor3=Color3.fromRGB(85,60,95);test.BackgroundTransparency=.08;test.Text="測試資料\n停止測試後不保存";test.TextWrapped=true;test.TextScaled=true;test.TextColor3=Color3.new(1,1,1);test.Visible=false;test.Parent=gui;local testConstraint=Instance.new("UISizeConstraint");testConstraint.MinSize=Vector2.new(145,38);testConstraint.MaxSize=Vector2.new(230,54);testConstraint.Parent=test
local daily=Instance.new("TextButton");daily.AnchorPoint=Vector2.new(1,0);daily.Position=UDim2.fromScale(.975,.11);daily.Size=UDim2.fromScale(.12,.055);daily.Text="每日獎勵";daily.TextScaled=true;daily.Selectable=true;daily.Parent=gui
updated.OnClientEvent:Connect(function(data)if data.loadFailed then coins.Text=data.message;return end;coins.Text="Coins "..tostring(data.coins or 0);wins.Text="Wins "..tostring(data.wins or 0);rank.Text=string.format("%s｜%d RP",data.rankId or"木桶村民 III",data.rankPoints or 0);test.Visible=data.memoryMode==true;gui:SetAttribute("SnapshotReceived",true)end)
daily.Activated:Connect(function()claim:FireServer()end);(remotes:WaitForChild("ModeStateChanged")::RemoteEvent).OnClientEvent:Connect(function(data)local lobby=data.inLobby==true or data.uiState=="Lobby";daily.Visible=lobby;rank.Visible=lobby end);request:FireServer()
